package cn.zxy.zmanager.dao.dataobject;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ZElectricMeterExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table z_electric_meter
     *
     * @mbg.generated Sat Oct 27 15:56:51 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table z_electric_meter
     *
     * @mbg.generated Sat Oct 27 15:56:51 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table z_electric_meter
     *
     * @mbg.generated Sat Oct 27 15:56:51 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_electric_meter
     *
     * @mbg.generated Sat Oct 27 15:56:51 CST 2018
     */
    public ZElectricMeterExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_electric_meter
     *
     * @mbg.generated Sat Oct 27 15:56:51 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_electric_meter
     *
     * @mbg.generated Sat Oct 27 15:56:51 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_electric_meter
     *
     * @mbg.generated Sat Oct 27 15:56:51 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_electric_meter
     *
     * @mbg.generated Sat Oct 27 15:56:51 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_electric_meter
     *
     * @mbg.generated Sat Oct 27 15:56:51 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_electric_meter
     *
     * @mbg.generated Sat Oct 27 15:56:51 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_electric_meter
     *
     * @mbg.generated Sat Oct 27 15:56:51 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_electric_meter
     *
     * @mbg.generated Sat Oct 27 15:56:51 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_electric_meter
     *
     * @mbg.generated Sat Oct 27 15:56:51 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_electric_meter
     *
     * @mbg.generated Sat Oct 27 15:56:51 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table z_electric_meter
     *
     * @mbg.generated Sat Oct 27 15:56:51 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andElectricMeterCodeIsNull() {
            addCriterion("electric_meter_code is null");
            return (Criteria) this;
        }

        public Criteria andElectricMeterCodeIsNotNull() {
            addCriterion("electric_meter_code is not null");
            return (Criteria) this;
        }

        public Criteria andElectricMeterCodeEqualTo(String value) {
            addCriterion("electric_meter_code =", value, "electricMeterCode");
            return (Criteria) this;
        }

        public Criteria andElectricMeterCodeNotEqualTo(String value) {
            addCriterion("electric_meter_code <>", value, "electricMeterCode");
            return (Criteria) this;
        }

        public Criteria andElectricMeterCodeGreaterThan(String value) {
            addCriterion("electric_meter_code >", value, "electricMeterCode");
            return (Criteria) this;
        }

        public Criteria andElectricMeterCodeGreaterThanOrEqualTo(String value) {
            addCriterion("electric_meter_code >=", value, "electricMeterCode");
            return (Criteria) this;
        }

        public Criteria andElectricMeterCodeLessThan(String value) {
            addCriterion("electric_meter_code <", value, "electricMeterCode");
            return (Criteria) this;
        }

        public Criteria andElectricMeterCodeLessThanOrEqualTo(String value) {
            addCriterion("electric_meter_code <=", value, "electricMeterCode");
            return (Criteria) this;
        }

        public Criteria andElectricMeterCodeLike(String value) {
            addCriterion("electric_meter_code like", value, "electricMeterCode");
            return (Criteria) this;
        }

        public Criteria andElectricMeterCodeNotLike(String value) {
            addCriterion("electric_meter_code not like", value, "electricMeterCode");
            return (Criteria) this;
        }

        public Criteria andElectricMeterCodeIn(List<String> values) {
            addCriterion("electric_meter_code in", values, "electricMeterCode");
            return (Criteria) this;
        }

        public Criteria andElectricMeterCodeNotIn(List<String> values) {
            addCriterion("electric_meter_code not in", values, "electricMeterCode");
            return (Criteria) this;
        }

        public Criteria andElectricMeterCodeBetween(String value1, String value2) {
            addCriterion("electric_meter_code between", value1, value2, "electricMeterCode");
            return (Criteria) this;
        }

        public Criteria andElectricMeterCodeNotBetween(String value1, String value2) {
            addCriterion("electric_meter_code not between", value1, value2, "electricMeterCode");
            return (Criteria) this;
        }

        public Criteria andContractIdIsNull() {
            addCriterion("contract_id is null");
            return (Criteria) this;
        }

        public Criteria andContractIdIsNotNull() {
            addCriterion("contract_id is not null");
            return (Criteria) this;
        }

        public Criteria andContractIdEqualTo(Integer value) {
            addCriterion("contract_id =", value, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdNotEqualTo(Integer value) {
            addCriterion("contract_id <>", value, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdGreaterThan(Integer value) {
            addCriterion("contract_id >", value, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("contract_id >=", value, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdLessThan(Integer value) {
            addCriterion("contract_id <", value, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdLessThanOrEqualTo(Integer value) {
            addCriterion("contract_id <=", value, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdIn(List<Integer> values) {
            addCriterion("contract_id in", values, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdNotIn(List<Integer> values) {
            addCriterion("contract_id not in", values, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdBetween(Integer value1, Integer value2) {
            addCriterion("contract_id between", value1, value2, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdNotBetween(Integer value1, Integer value2) {
            addCriterion("contract_id not between", value1, value2, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractCodeIsNull() {
            addCriterion("contract_code is null");
            return (Criteria) this;
        }

        public Criteria andContractCodeIsNotNull() {
            addCriterion("contract_code is not null");
            return (Criteria) this;
        }

        public Criteria andContractCodeEqualTo(String value) {
            addCriterion("contract_code =", value, "contractCode");
            return (Criteria) this;
        }

        public Criteria andContractCodeNotEqualTo(String value) {
            addCriterion("contract_code <>", value, "contractCode");
            return (Criteria) this;
        }

        public Criteria andContractCodeGreaterThan(String value) {
            addCriterion("contract_code >", value, "contractCode");
            return (Criteria) this;
        }

        public Criteria andContractCodeGreaterThanOrEqualTo(String value) {
            addCriterion("contract_code >=", value, "contractCode");
            return (Criteria) this;
        }

        public Criteria andContractCodeLessThan(String value) {
            addCriterion("contract_code <", value, "contractCode");
            return (Criteria) this;
        }

        public Criteria andContractCodeLessThanOrEqualTo(String value) {
            addCriterion("contract_code <=", value, "contractCode");
            return (Criteria) this;
        }

        public Criteria andContractCodeLike(String value) {
            addCriterion("contract_code like", value, "contractCode");
            return (Criteria) this;
        }

        public Criteria andContractCodeNotLike(String value) {
            addCriterion("contract_code not like", value, "contractCode");
            return (Criteria) this;
        }

        public Criteria andContractCodeIn(List<String> values) {
            addCriterion("contract_code in", values, "contractCode");
            return (Criteria) this;
        }

        public Criteria andContractCodeNotIn(List<String> values) {
            addCriterion("contract_code not in", values, "contractCode");
            return (Criteria) this;
        }

        public Criteria andContractCodeBetween(String value1, String value2) {
            addCriterion("contract_code between", value1, value2, "contractCode");
            return (Criteria) this;
        }

        public Criteria andContractCodeNotBetween(String value1, String value2) {
            addCriterion("contract_code not between", value1, value2, "contractCode");
            return (Criteria) this;
        }

        public Criteria andVoltageIsNull() {
            addCriterion("voltage is null");
            return (Criteria) this;
        }

        public Criteria andVoltageIsNotNull() {
            addCriterion("voltage is not null");
            return (Criteria) this;
        }

        public Criteria andVoltageEqualTo(Integer value) {
            addCriterion("voltage =", value, "voltage");
            return (Criteria) this;
        }

        public Criteria andVoltageNotEqualTo(Integer value) {
            addCriterion("voltage <>", value, "voltage");
            return (Criteria) this;
        }

        public Criteria andVoltageGreaterThan(Integer value) {
            addCriterion("voltage >", value, "voltage");
            return (Criteria) this;
        }

        public Criteria andVoltageGreaterThanOrEqualTo(Integer value) {
            addCriterion("voltage >=", value, "voltage");
            return (Criteria) this;
        }

        public Criteria andVoltageLessThan(Integer value) {
            addCriterion("voltage <", value, "voltage");
            return (Criteria) this;
        }

        public Criteria andVoltageLessThanOrEqualTo(Integer value) {
            addCriterion("voltage <=", value, "voltage");
            return (Criteria) this;
        }

        public Criteria andVoltageIn(List<Integer> values) {
            addCriterion("voltage in", values, "voltage");
            return (Criteria) this;
        }

        public Criteria andVoltageNotIn(List<Integer> values) {
            addCriterion("voltage not in", values, "voltage");
            return (Criteria) this;
        }

        public Criteria andVoltageBetween(Integer value1, Integer value2) {
            addCriterion("voltage between", value1, value2, "voltage");
            return (Criteria) this;
        }

        public Criteria andVoltageNotBetween(Integer value1, Integer value2) {
            addCriterion("voltage not between", value1, value2, "voltage");
            return (Criteria) this;
        }

        public Criteria andElectricCurrentIsNull() {
            addCriterion("electric_current is null");
            return (Criteria) this;
        }

        public Criteria andElectricCurrentIsNotNull() {
            addCriterion("electric_current is not null");
            return (Criteria) this;
        }

        public Criteria andElectricCurrentEqualTo(Integer value) {
            addCriterion("electric_current =", value, "electricCurrent");
            return (Criteria) this;
        }

        public Criteria andElectricCurrentNotEqualTo(Integer value) {
            addCriterion("electric_current <>", value, "electricCurrent");
            return (Criteria) this;
        }

        public Criteria andElectricCurrentGreaterThan(Integer value) {
            addCriterion("electric_current >", value, "electricCurrent");
            return (Criteria) this;
        }

        public Criteria andElectricCurrentGreaterThanOrEqualTo(Integer value) {
            addCriterion("electric_current >=", value, "electricCurrent");
            return (Criteria) this;
        }

        public Criteria andElectricCurrentLessThan(Integer value) {
            addCriterion("electric_current <", value, "electricCurrent");
            return (Criteria) this;
        }

        public Criteria andElectricCurrentLessThanOrEqualTo(Integer value) {
            addCriterion("electric_current <=", value, "electricCurrent");
            return (Criteria) this;
        }

        public Criteria andElectricCurrentIn(List<Integer> values) {
            addCriterion("electric_current in", values, "electricCurrent");
            return (Criteria) this;
        }

        public Criteria andElectricCurrentNotIn(List<Integer> values) {
            addCriterion("electric_current not in", values, "electricCurrent");
            return (Criteria) this;
        }

        public Criteria andElectricCurrentBetween(Integer value1, Integer value2) {
            addCriterion("electric_current between", value1, value2, "electricCurrent");
            return (Criteria) this;
        }

        public Criteria andElectricCurrentNotBetween(Integer value1, Integer value2) {
            addCriterion("electric_current not between", value1, value2, "electricCurrent");
            return (Criteria) this;
        }

        public Criteria andMagnificationIsNull() {
            addCriterion("magnification is null");
            return (Criteria) this;
        }

        public Criteria andMagnificationIsNotNull() {
            addCriterion("magnification is not null");
            return (Criteria) this;
        }

        public Criteria andMagnificationEqualTo(Integer value) {
            addCriterion("magnification =", value, "magnification");
            return (Criteria) this;
        }

        public Criteria andMagnificationNotEqualTo(Integer value) {
            addCriterion("magnification <>", value, "magnification");
            return (Criteria) this;
        }

        public Criteria andMagnificationGreaterThan(Integer value) {
            addCriterion("magnification >", value, "magnification");
            return (Criteria) this;
        }

        public Criteria andMagnificationGreaterThanOrEqualTo(Integer value) {
            addCriterion("magnification >=", value, "magnification");
            return (Criteria) this;
        }

        public Criteria andMagnificationLessThan(Integer value) {
            addCriterion("magnification <", value, "magnification");
            return (Criteria) this;
        }

        public Criteria andMagnificationLessThanOrEqualTo(Integer value) {
            addCriterion("magnification <=", value, "magnification");
            return (Criteria) this;
        }

        public Criteria andMagnificationIn(List<Integer> values) {
            addCriterion("magnification in", values, "magnification");
            return (Criteria) this;
        }

        public Criteria andMagnificationNotIn(List<Integer> values) {
            addCriterion("magnification not in", values, "magnification");
            return (Criteria) this;
        }

        public Criteria andMagnificationBetween(Integer value1, Integer value2) {
            addCriterion("magnification between", value1, value2, "magnification");
            return (Criteria) this;
        }

        public Criteria andMagnificationNotBetween(Integer value1, Integer value2) {
            addCriterion("magnification not between", value1, value2, "magnification");
            return (Criteria) this;
        }

        public Criteria andInitMarkIsNull() {
            addCriterion("init_mark is null");
            return (Criteria) this;
        }

        public Criteria andInitMarkIsNotNull() {
            addCriterion("init_mark is not null");
            return (Criteria) this;
        }

        public Criteria andInitMarkEqualTo(Integer value) {
            addCriterion("init_mark =", value, "initMark");
            return (Criteria) this;
        }

        public Criteria andInitMarkNotEqualTo(Integer value) {
            addCriterion("init_mark <>", value, "initMark");
            return (Criteria) this;
        }

        public Criteria andInitMarkGreaterThan(Integer value) {
            addCriterion("init_mark >", value, "initMark");
            return (Criteria) this;
        }

        public Criteria andInitMarkGreaterThanOrEqualTo(Integer value) {
            addCriterion("init_mark >=", value, "initMark");
            return (Criteria) this;
        }

        public Criteria andInitMarkLessThan(Integer value) {
            addCriterion("init_mark <", value, "initMark");
            return (Criteria) this;
        }

        public Criteria andInitMarkLessThanOrEqualTo(Integer value) {
            addCriterion("init_mark <=", value, "initMark");
            return (Criteria) this;
        }

        public Criteria andInitMarkIn(List<Integer> values) {
            addCriterion("init_mark in", values, "initMark");
            return (Criteria) this;
        }

        public Criteria andInitMarkNotIn(List<Integer> values) {
            addCriterion("init_mark not in", values, "initMark");
            return (Criteria) this;
        }

        public Criteria andInitMarkBetween(Integer value1, Integer value2) {
            addCriterion("init_mark between", value1, value2, "initMark");
            return (Criteria) this;
        }

        public Criteria andInitMarkNotBetween(Integer value1, Integer value2) {
            addCriterion("init_mark not between", value1, value2, "initMark");
            return (Criteria) this;
        }

        public Criteria andElectricFeeIsNull() {
            addCriterion("electric_fee is null");
            return (Criteria) this;
        }

        public Criteria andElectricFeeIsNotNull() {
            addCriterion("electric_fee is not null");
            return (Criteria) this;
        }

        public Criteria andElectricFeeEqualTo(Integer value) {
            addCriterion("electric_fee =", value, "electricFee");
            return (Criteria) this;
        }

        public Criteria andElectricFeeNotEqualTo(Integer value) {
            addCriterion("electric_fee <>", value, "electricFee");
            return (Criteria) this;
        }

        public Criteria andElectricFeeGreaterThan(Integer value) {
            addCriterion("electric_fee >", value, "electricFee");
            return (Criteria) this;
        }

        public Criteria andElectricFeeGreaterThanOrEqualTo(Integer value) {
            addCriterion("electric_fee >=", value, "electricFee");
            return (Criteria) this;
        }

        public Criteria andElectricFeeLessThan(Integer value) {
            addCriterion("electric_fee <", value, "electricFee");
            return (Criteria) this;
        }

        public Criteria andElectricFeeLessThanOrEqualTo(Integer value) {
            addCriterion("electric_fee <=", value, "electricFee");
            return (Criteria) this;
        }

        public Criteria andElectricFeeIn(List<Integer> values) {
            addCriterion("electric_fee in", values, "electricFee");
            return (Criteria) this;
        }

        public Criteria andElectricFeeNotIn(List<Integer> values) {
            addCriterion("electric_fee not in", values, "electricFee");
            return (Criteria) this;
        }

        public Criteria andElectricFeeBetween(Integer value1, Integer value2) {
            addCriterion("electric_fee between", value1, value2, "electricFee");
            return (Criteria) this;
        }

        public Criteria andElectricFeeNotBetween(Integer value1, Integer value2) {
            addCriterion("electric_fee not between", value1, value2, "electricFee");
            return (Criteria) this;
        }

        public Criteria andTotalUseElectricIsNull() {
            addCriterion("total_use_electric is null");
            return (Criteria) this;
        }

        public Criteria andTotalUseElectricIsNotNull() {
            addCriterion("total_use_electric is not null");
            return (Criteria) this;
        }

        public Criteria andTotalUseElectricEqualTo(Integer value) {
            addCriterion("total_use_electric =", value, "totalUseElectric");
            return (Criteria) this;
        }

        public Criteria andTotalUseElectricNotEqualTo(Integer value) {
            addCriterion("total_use_electric <>", value, "totalUseElectric");
            return (Criteria) this;
        }

        public Criteria andTotalUseElectricGreaterThan(Integer value) {
            addCriterion("total_use_electric >", value, "totalUseElectric");
            return (Criteria) this;
        }

        public Criteria andTotalUseElectricGreaterThanOrEqualTo(Integer value) {
            addCriterion("total_use_electric >=", value, "totalUseElectric");
            return (Criteria) this;
        }

        public Criteria andTotalUseElectricLessThan(Integer value) {
            addCriterion("total_use_electric <", value, "totalUseElectric");
            return (Criteria) this;
        }

        public Criteria andTotalUseElectricLessThanOrEqualTo(Integer value) {
            addCriterion("total_use_electric <=", value, "totalUseElectric");
            return (Criteria) this;
        }

        public Criteria andTotalUseElectricIn(List<Integer> values) {
            addCriterion("total_use_electric in", values, "totalUseElectric");
            return (Criteria) this;
        }

        public Criteria andTotalUseElectricNotIn(List<Integer> values) {
            addCriterion("total_use_electric not in", values, "totalUseElectric");
            return (Criteria) this;
        }

        public Criteria andTotalUseElectricBetween(Integer value1, Integer value2) {
            addCriterion("total_use_electric between", value1, value2, "totalUseElectric");
            return (Criteria) this;
        }

        public Criteria andTotalUseElectricNotBetween(Integer value1, Integer value2) {
            addCriterion("total_use_electric not between", value1, value2, "totalUseElectric");
            return (Criteria) this;
        }

        public Criteria andTotalPaidElectricIsNull() {
            addCriterion("total_paid_electric is null");
            return (Criteria) this;
        }

        public Criteria andTotalPaidElectricIsNotNull() {
            addCriterion("total_paid_electric is not null");
            return (Criteria) this;
        }

        public Criteria andTotalPaidElectricEqualTo(Integer value) {
            addCriterion("total_paid_electric =", value, "totalPaidElectric");
            return (Criteria) this;
        }

        public Criteria andTotalPaidElectricNotEqualTo(Integer value) {
            addCriterion("total_paid_electric <>", value, "totalPaidElectric");
            return (Criteria) this;
        }

        public Criteria andTotalPaidElectricGreaterThan(Integer value) {
            addCriterion("total_paid_electric >", value, "totalPaidElectric");
            return (Criteria) this;
        }

        public Criteria andTotalPaidElectricGreaterThanOrEqualTo(Integer value) {
            addCriterion("total_paid_electric >=", value, "totalPaidElectric");
            return (Criteria) this;
        }

        public Criteria andTotalPaidElectricLessThan(Integer value) {
            addCriterion("total_paid_electric <", value, "totalPaidElectric");
            return (Criteria) this;
        }

        public Criteria andTotalPaidElectricLessThanOrEqualTo(Integer value) {
            addCriterion("total_paid_electric <=", value, "totalPaidElectric");
            return (Criteria) this;
        }

        public Criteria andTotalPaidElectricIn(List<Integer> values) {
            addCriterion("total_paid_electric in", values, "totalPaidElectric");
            return (Criteria) this;
        }

        public Criteria andTotalPaidElectricNotIn(List<Integer> values) {
            addCriterion("total_paid_electric not in", values, "totalPaidElectric");
            return (Criteria) this;
        }

        public Criteria andTotalPaidElectricBetween(Integer value1, Integer value2) {
            addCriterion("total_paid_electric between", value1, value2, "totalPaidElectric");
            return (Criteria) this;
        }

        public Criteria andTotalPaidElectricNotBetween(Integer value1, Integer value2) {
            addCriterion("total_paid_electric not between", value1, value2, "totalPaidElectric");
            return (Criteria) this;
        }

        public Criteria andTotalUseElectricFeeIsNull() {
            addCriterion("total_use_electric_fee is null");
            return (Criteria) this;
        }

        public Criteria andTotalUseElectricFeeIsNotNull() {
            addCriterion("total_use_electric_fee is not null");
            return (Criteria) this;
        }

        public Criteria andTotalUseElectricFeeEqualTo(Integer value) {
            addCriterion("total_use_electric_fee =", value, "totalUseElectricFee");
            return (Criteria) this;
        }

        public Criteria andTotalUseElectricFeeNotEqualTo(Integer value) {
            addCriterion("total_use_electric_fee <>", value, "totalUseElectricFee");
            return (Criteria) this;
        }

        public Criteria andTotalUseElectricFeeGreaterThan(Integer value) {
            addCriterion("total_use_electric_fee >", value, "totalUseElectricFee");
            return (Criteria) this;
        }

        public Criteria andTotalUseElectricFeeGreaterThanOrEqualTo(Integer value) {
            addCriterion("total_use_electric_fee >=", value, "totalUseElectricFee");
            return (Criteria) this;
        }

        public Criteria andTotalUseElectricFeeLessThan(Integer value) {
            addCriterion("total_use_electric_fee <", value, "totalUseElectricFee");
            return (Criteria) this;
        }

        public Criteria andTotalUseElectricFeeLessThanOrEqualTo(Integer value) {
            addCriterion("total_use_electric_fee <=", value, "totalUseElectricFee");
            return (Criteria) this;
        }

        public Criteria andTotalUseElectricFeeIn(List<Integer> values) {
            addCriterion("total_use_electric_fee in", values, "totalUseElectricFee");
            return (Criteria) this;
        }

        public Criteria andTotalUseElectricFeeNotIn(List<Integer> values) {
            addCriterion("total_use_electric_fee not in", values, "totalUseElectricFee");
            return (Criteria) this;
        }

        public Criteria andTotalUseElectricFeeBetween(Integer value1, Integer value2) {
            addCriterion("total_use_electric_fee between", value1, value2, "totalUseElectricFee");
            return (Criteria) this;
        }

        public Criteria andTotalUseElectricFeeNotBetween(Integer value1, Integer value2) {
            addCriterion("total_use_electric_fee not between", value1, value2, "totalUseElectricFee");
            return (Criteria) this;
        }

        public Criteria andTotalPaidElectricFeeIsNull() {
            addCriterion("total_paid_electric_fee is null");
            return (Criteria) this;
        }

        public Criteria andTotalPaidElectricFeeIsNotNull() {
            addCriterion("total_paid_electric_fee is not null");
            return (Criteria) this;
        }

        public Criteria andTotalPaidElectricFeeEqualTo(Integer value) {
            addCriterion("total_paid_electric_fee =", value, "totalPaidElectricFee");
            return (Criteria) this;
        }

        public Criteria andTotalPaidElectricFeeNotEqualTo(Integer value) {
            addCriterion("total_paid_electric_fee <>", value, "totalPaidElectricFee");
            return (Criteria) this;
        }

        public Criteria andTotalPaidElectricFeeGreaterThan(Integer value) {
            addCriterion("total_paid_electric_fee >", value, "totalPaidElectricFee");
            return (Criteria) this;
        }

        public Criteria andTotalPaidElectricFeeGreaterThanOrEqualTo(Integer value) {
            addCriterion("total_paid_electric_fee >=", value, "totalPaidElectricFee");
            return (Criteria) this;
        }

        public Criteria andTotalPaidElectricFeeLessThan(Integer value) {
            addCriterion("total_paid_electric_fee <", value, "totalPaidElectricFee");
            return (Criteria) this;
        }

        public Criteria andTotalPaidElectricFeeLessThanOrEqualTo(Integer value) {
            addCriterion("total_paid_electric_fee <=", value, "totalPaidElectricFee");
            return (Criteria) this;
        }

        public Criteria andTotalPaidElectricFeeIn(List<Integer> values) {
            addCriterion("total_paid_electric_fee in", values, "totalPaidElectricFee");
            return (Criteria) this;
        }

        public Criteria andTotalPaidElectricFeeNotIn(List<Integer> values) {
            addCriterion("total_paid_electric_fee not in", values, "totalPaidElectricFee");
            return (Criteria) this;
        }

        public Criteria andTotalPaidElectricFeeBetween(Integer value1, Integer value2) {
            addCriterion("total_paid_electric_fee between", value1, value2, "totalPaidElectricFee");
            return (Criteria) this;
        }

        public Criteria andTotalPaidElectricFeeNotBetween(Integer value1, Integer value2) {
            addCriterion("total_paid_electric_fee not between", value1, value2, "totalPaidElectricFee");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andRemarksIsNull() {
            addCriterion("remarks is null");
            return (Criteria) this;
        }

        public Criteria andRemarksIsNotNull() {
            addCriterion("remarks is not null");
            return (Criteria) this;
        }

        public Criteria andRemarksEqualTo(String value) {
            addCriterion("remarks =", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotEqualTo(String value) {
            addCriterion("remarks <>", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksGreaterThan(String value) {
            addCriterion("remarks >", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksGreaterThanOrEqualTo(String value) {
            addCriterion("remarks >=", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLessThan(String value) {
            addCriterion("remarks <", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLessThanOrEqualTo(String value) {
            addCriterion("remarks <=", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLike(String value) {
            addCriterion("remarks like", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotLike(String value) {
            addCriterion("remarks not like", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksIn(List<String> values) {
            addCriterion("remarks in", values, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotIn(List<String> values) {
            addCriterion("remarks not in", values, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksBetween(String value1, String value2) {
            addCriterion("remarks between", value1, value2, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotBetween(String value1, String value2) {
            addCriterion("remarks not between", value1, value2, "remarks");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateEmpIdIsNull() {
            addCriterion("create_emp_id is null");
            return (Criteria) this;
        }

        public Criteria andCreateEmpIdIsNotNull() {
            addCriterion("create_emp_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreateEmpIdEqualTo(Integer value) {
            addCriterion("create_emp_id =", value, "createEmpId");
            return (Criteria) this;
        }

        public Criteria andCreateEmpIdNotEqualTo(Integer value) {
            addCriterion("create_emp_id <>", value, "createEmpId");
            return (Criteria) this;
        }

        public Criteria andCreateEmpIdGreaterThan(Integer value) {
            addCriterion("create_emp_id >", value, "createEmpId");
            return (Criteria) this;
        }

        public Criteria andCreateEmpIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("create_emp_id >=", value, "createEmpId");
            return (Criteria) this;
        }

        public Criteria andCreateEmpIdLessThan(Integer value) {
            addCriterion("create_emp_id <", value, "createEmpId");
            return (Criteria) this;
        }

        public Criteria andCreateEmpIdLessThanOrEqualTo(Integer value) {
            addCriterion("create_emp_id <=", value, "createEmpId");
            return (Criteria) this;
        }

        public Criteria andCreateEmpIdIn(List<Integer> values) {
            addCriterion("create_emp_id in", values, "createEmpId");
            return (Criteria) this;
        }

        public Criteria andCreateEmpIdNotIn(List<Integer> values) {
            addCriterion("create_emp_id not in", values, "createEmpId");
            return (Criteria) this;
        }

        public Criteria andCreateEmpIdBetween(Integer value1, Integer value2) {
            addCriterion("create_emp_id between", value1, value2, "createEmpId");
            return (Criteria) this;
        }

        public Criteria andCreateEmpIdNotBetween(Integer value1, Integer value2) {
            addCriterion("create_emp_id not between", value1, value2, "createEmpId");
            return (Criteria) this;
        }

        public Criteria andCreateEmpIsNull() {
            addCriterion("create_emp is null");
            return (Criteria) this;
        }

        public Criteria andCreateEmpIsNotNull() {
            addCriterion("create_emp is not null");
            return (Criteria) this;
        }

        public Criteria andCreateEmpEqualTo(String value) {
            addCriterion("create_emp =", value, "createEmp");
            return (Criteria) this;
        }

        public Criteria andCreateEmpNotEqualTo(String value) {
            addCriterion("create_emp <>", value, "createEmp");
            return (Criteria) this;
        }

        public Criteria andCreateEmpGreaterThan(String value) {
            addCriterion("create_emp >", value, "createEmp");
            return (Criteria) this;
        }

        public Criteria andCreateEmpGreaterThanOrEqualTo(String value) {
            addCriterion("create_emp >=", value, "createEmp");
            return (Criteria) this;
        }

        public Criteria andCreateEmpLessThan(String value) {
            addCriterion("create_emp <", value, "createEmp");
            return (Criteria) this;
        }

        public Criteria andCreateEmpLessThanOrEqualTo(String value) {
            addCriterion("create_emp <=", value, "createEmp");
            return (Criteria) this;
        }

        public Criteria andCreateEmpLike(String value) {
            addCriterion("create_emp like", value, "createEmp");
            return (Criteria) this;
        }

        public Criteria andCreateEmpNotLike(String value) {
            addCriterion("create_emp not like", value, "createEmp");
            return (Criteria) this;
        }

        public Criteria andCreateEmpIn(List<String> values) {
            addCriterion("create_emp in", values, "createEmp");
            return (Criteria) this;
        }

        public Criteria andCreateEmpNotIn(List<String> values) {
            addCriterion("create_emp not in", values, "createEmp");
            return (Criteria) this;
        }

        public Criteria andCreateEmpBetween(String value1, String value2) {
            addCriterion("create_emp between", value1, value2, "createEmp");
            return (Criteria) this;
        }

        public Criteria andCreateEmpNotBetween(String value1, String value2) {
            addCriterion("create_emp not between", value1, value2, "createEmp");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNull() {
            addCriterion("modify_time is null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNotNull() {
            addCriterion("modify_time is not null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeEqualTo(Date value) {
            addCriterion("modify_time =", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotEqualTo(Date value) {
            addCriterion("modify_time <>", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThan(Date value) {
            addCriterion("modify_time >", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("modify_time >=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThan(Date value) {
            addCriterion("modify_time <", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThanOrEqualTo(Date value) {
            addCriterion("modify_time <=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIn(List<Date> values) {
            addCriterion("modify_time in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotIn(List<Date> values) {
            addCriterion("modify_time not in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeBetween(Date value1, Date value2) {
            addCriterion("modify_time between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotBetween(Date value1, Date value2) {
            addCriterion("modify_time not between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyEmpIdIsNull() {
            addCriterion("modify_emp_id is null");
            return (Criteria) this;
        }

        public Criteria andModifyEmpIdIsNotNull() {
            addCriterion("modify_emp_id is not null");
            return (Criteria) this;
        }

        public Criteria andModifyEmpIdEqualTo(Integer value) {
            addCriterion("modify_emp_id =", value, "modifyEmpId");
            return (Criteria) this;
        }

        public Criteria andModifyEmpIdNotEqualTo(Integer value) {
            addCriterion("modify_emp_id <>", value, "modifyEmpId");
            return (Criteria) this;
        }

        public Criteria andModifyEmpIdGreaterThan(Integer value) {
            addCriterion("modify_emp_id >", value, "modifyEmpId");
            return (Criteria) this;
        }

        public Criteria andModifyEmpIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("modify_emp_id >=", value, "modifyEmpId");
            return (Criteria) this;
        }

        public Criteria andModifyEmpIdLessThan(Integer value) {
            addCriterion("modify_emp_id <", value, "modifyEmpId");
            return (Criteria) this;
        }

        public Criteria andModifyEmpIdLessThanOrEqualTo(Integer value) {
            addCriterion("modify_emp_id <=", value, "modifyEmpId");
            return (Criteria) this;
        }

        public Criteria andModifyEmpIdIn(List<Integer> values) {
            addCriterion("modify_emp_id in", values, "modifyEmpId");
            return (Criteria) this;
        }

        public Criteria andModifyEmpIdNotIn(List<Integer> values) {
            addCriterion("modify_emp_id not in", values, "modifyEmpId");
            return (Criteria) this;
        }

        public Criteria andModifyEmpIdBetween(Integer value1, Integer value2) {
            addCriterion("modify_emp_id between", value1, value2, "modifyEmpId");
            return (Criteria) this;
        }

        public Criteria andModifyEmpIdNotBetween(Integer value1, Integer value2) {
            addCriterion("modify_emp_id not between", value1, value2, "modifyEmpId");
            return (Criteria) this;
        }

        public Criteria andModifyEmpIsNull() {
            addCriterion("modify_emp is null");
            return (Criteria) this;
        }

        public Criteria andModifyEmpIsNotNull() {
            addCriterion("modify_emp is not null");
            return (Criteria) this;
        }

        public Criteria andModifyEmpEqualTo(String value) {
            addCriterion("modify_emp =", value, "modifyEmp");
            return (Criteria) this;
        }

        public Criteria andModifyEmpNotEqualTo(String value) {
            addCriterion("modify_emp <>", value, "modifyEmp");
            return (Criteria) this;
        }

        public Criteria andModifyEmpGreaterThan(String value) {
            addCriterion("modify_emp >", value, "modifyEmp");
            return (Criteria) this;
        }

        public Criteria andModifyEmpGreaterThanOrEqualTo(String value) {
            addCriterion("modify_emp >=", value, "modifyEmp");
            return (Criteria) this;
        }

        public Criteria andModifyEmpLessThan(String value) {
            addCriterion("modify_emp <", value, "modifyEmp");
            return (Criteria) this;
        }

        public Criteria andModifyEmpLessThanOrEqualTo(String value) {
            addCriterion("modify_emp <=", value, "modifyEmp");
            return (Criteria) this;
        }

        public Criteria andModifyEmpLike(String value) {
            addCriterion("modify_emp like", value, "modifyEmp");
            return (Criteria) this;
        }

        public Criteria andModifyEmpNotLike(String value) {
            addCriterion("modify_emp not like", value, "modifyEmp");
            return (Criteria) this;
        }

        public Criteria andModifyEmpIn(List<String> values) {
            addCriterion("modify_emp in", values, "modifyEmp");
            return (Criteria) this;
        }

        public Criteria andModifyEmpNotIn(List<String> values) {
            addCriterion("modify_emp not in", values, "modifyEmp");
            return (Criteria) this;
        }

        public Criteria andModifyEmpBetween(String value1, String value2) {
            addCriterion("modify_emp between", value1, value2, "modifyEmp");
            return (Criteria) this;
        }

        public Criteria andModifyEmpNotBetween(String value1, String value2) {
            addCriterion("modify_emp not between", value1, value2, "modifyEmp");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table z_electric_meter
     *
     * @mbg.generated do_not_delete_during_merge Sat Oct 27 15:56:51 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table z_electric_meter
     *
     * @mbg.generated Sat Oct 27 15:56:51 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}