package cn.zxy.zmanager.dao.dataobject;

import java.util.Date;

public class ZElectricMeter {
	/** 状态：停用 */
	public static final Integer STOP_STATUS = 0;
	
	/** 状态：使用中 */
    public static final Integer USING_STATUS = 1;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_electric_meter.id
     *
     * @mbg.generated Wed Oct 24 00:12:40 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_electric_meter.electric_meter_code
     *
     * @mbg.generated Wed Oct 24 00:12:40 CST 2018
     */
    private String electricMeterCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_electric_meter.contract_id
     *
     * @mbg.generated Wed Oct 24 00:12:40 CST 2018
     */
    private Integer contractId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_electric_meter. contract_code
     *
     * @mbg.generated Wed Oct 24 00:12:40 CST 2018
     */
    private String contractCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_electric_meter.voltage
     *
     * @mbg.generated Wed Oct 24 00:12:40 CST 2018
     */
    private Integer voltage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_electric_meter.electric_current
     *
     * @mbg.generated Wed Oct 24 00:12:40 CST 2018
     */
    private Integer electricCurrent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_electric_meter.magnification
     *
     * @mbg.generated Wed Oct 24 00:12:40 CST 2018
     */
    private Integer magnification;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_electric_meter.init_mark
     *
     * @mbg.generated Wed Oct 24 00:12:40 CST 2018
     */
    private Integer initMark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_electric_meter.total_electric
     *
     * @mbg.generated Wed Oct 24 00:12:40 CST 2018
     */
    private Integer totalElectric;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_electric_meter.electric_fee
     *
     * @mbg.generated Wed Oct 24 00:12:40 CST 2018
     */
    private Integer electricFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_electric_meter.status
     *
     * @mbg.generated Wed Oct 24 00:12:40 CST 2018
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_electric_meter.remarks
     *
     * @mbg.generated Wed Oct 24 00:12:40 CST 2018
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_electric_meter.create_time
     *
     * @mbg.generated Wed Oct 24 00:12:40 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_electric_meter.create_emp_id
     *
     * @mbg.generated Wed Oct 24 00:12:40 CST 2018
     */
    private Integer createEmpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_electric_meter.create_emp
     *
     * @mbg.generated Wed Oct 24 00:12:40 CST 2018
     */
    private String createEmp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_electric_meter.modify_time
     *
     * @mbg.generated Wed Oct 24 00:12:40 CST 2018
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_electric_meter.modify_emp_id
     *
     * @mbg.generated Wed Oct 24 00:12:40 CST 2018
     */
    private Integer modifyEmpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_electric_meter.modify_emp
     *
     * @mbg.generated Wed Oct 24 00:12:40 CST 2018
     */
    private String modifyEmp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_electric_meter.id
     *
     * @return the value of z_electric_meter.id
     *
     * @mbg.generated Wed Oct 24 00:12:40 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_electric_meter.id
     *
     * @param id the value for z_electric_meter.id
     *
     * @mbg.generated Wed Oct 24 00:12:40 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_electric_meter.electric_meter_code
     *
     * @return the value of z_electric_meter.electric_meter_code
     *
     * @mbg.generated Wed Oct 24 00:12:40 CST 2018
     */
    public String getElectricMeterCode() {
        return electricMeterCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_electric_meter.electric_meter_code
     *
     * @param electricMeterCode the value for z_electric_meter.electric_meter_code
     *
     * @mbg.generated Wed Oct 24 00:12:40 CST 2018
     */
    public void setElectricMeterCode(String electricMeterCode) {
        this.electricMeterCode = electricMeterCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_electric_meter.contract_id
     *
     * @return the value of z_electric_meter.contract_id
     *
     * @mbg.generated Wed Oct 24 00:12:40 CST 2018
     */
    public Integer getContractId() {
        return contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_electric_meter.contract_id
     *
     * @param contractId the value for z_electric_meter.contract_id
     *
     * @mbg.generated Wed Oct 24 00:12:40 CST 2018
     */
    public void setContractId(Integer contractId) {
        this.contractId = contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_electric_meter. contract_code
     *
     * @return the value of z_electric_meter. contract_code
     *
     * @mbg.generated Wed Oct 24 00:12:40 CST 2018
     */
    public String getContractCode() {
        return contractCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_electric_meter. contract_code
     *
     * @param contractCode the value for z_electric_meter. contract_code
     *
     * @mbg.generated Wed Oct 24 00:12:40 CST 2018
     */
    public void setContractCode(String contractCode) {
        this.contractCode = contractCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_electric_meter.voltage
     *
     * @return the value of z_electric_meter.voltage
     *
     * @mbg.generated Wed Oct 24 00:12:40 CST 2018
     */
    public Integer getVoltage() {
        return voltage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_electric_meter.voltage
     *
     * @param voltage the value for z_electric_meter.voltage
     *
     * @mbg.generated Wed Oct 24 00:12:40 CST 2018
     */
    public void setVoltage(Integer voltage) {
        this.voltage = voltage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_electric_meter.electric_current
     *
     * @return the value of z_electric_meter.electric_current
     *
     * @mbg.generated Wed Oct 24 00:12:40 CST 2018
     */
    public Integer getElectricCurrent() {
        return electricCurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_electric_meter.electric_current
     *
     * @param electricCurrent the value for z_electric_meter.electric_current
     *
     * @mbg.generated Wed Oct 24 00:12:40 CST 2018
     */
    public void setElectricCurrent(Integer electricCurrent) {
        this.electricCurrent = electricCurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_electric_meter.magnification
     *
     * @return the value of z_electric_meter.magnification
     *
     * @mbg.generated Wed Oct 24 00:12:40 CST 2018
     */
    public Integer getMagnification() {
        return magnification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_electric_meter.magnification
     *
     * @param magnification the value for z_electric_meter.magnification
     *
     * @mbg.generated Wed Oct 24 00:12:40 CST 2018
     */
    public void setMagnification(Integer magnification) {
        this.magnification = magnification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_electric_meter.init_mark
     *
     * @return the value of z_electric_meter.init_mark
     *
     * @mbg.generated Wed Oct 24 00:12:40 CST 2018
     */
    public Integer getInitMark() {
        return initMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_electric_meter.init_mark
     *
     * @param initMark the value for z_electric_meter.init_mark
     *
     * @mbg.generated Wed Oct 24 00:12:40 CST 2018
     */
    public void setInitMark(Integer initMark) {
        this.initMark = initMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_electric_meter.total_electric
     *
     * @return the value of z_electric_meter.total_electric
     *
     * @mbg.generated Wed Oct 24 00:12:40 CST 2018
     */
    public Integer getTotalElectric() {
        return totalElectric;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_electric_meter.total_electric
     *
     * @param totalElectric the value for z_electric_meter.total_electric
     *
     * @mbg.generated Wed Oct 24 00:12:40 CST 2018
     */
    public void setTotalElectric(Integer totalElectric) {
        this.totalElectric = totalElectric;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_electric_meter.electric_fee
     *
     * @return the value of z_electric_meter.electric_fee
     *
     * @mbg.generated Wed Oct 24 00:12:40 CST 2018
     */
    public Integer getElectricFee() {
        return electricFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_electric_meter.electric_fee
     *
     * @param electricFee the value for z_electric_meter.electric_fee
     *
     * @mbg.generated Wed Oct 24 00:12:40 CST 2018
     */
    public void setElectricFee(Integer electricFee) {
        this.electricFee = electricFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_electric_meter.status
     *
     * @return the value of z_electric_meter.status
     *
     * @mbg.generated Wed Oct 24 00:12:40 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_electric_meter.status
     *
     * @param status the value for z_electric_meter.status
     *
     * @mbg.generated Wed Oct 24 00:12:40 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_electric_meter.remarks
     *
     * @return the value of z_electric_meter.remarks
     *
     * @mbg.generated Wed Oct 24 00:12:40 CST 2018
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_electric_meter.remarks
     *
     * @param remarks the value for z_electric_meter.remarks
     *
     * @mbg.generated Wed Oct 24 00:12:40 CST 2018
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_electric_meter.create_time
     *
     * @return the value of z_electric_meter.create_time
     *
     * @mbg.generated Wed Oct 24 00:12:40 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_electric_meter.create_time
     *
     * @param createTime the value for z_electric_meter.create_time
     *
     * @mbg.generated Wed Oct 24 00:12:40 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_electric_meter.create_emp_id
     *
     * @return the value of z_electric_meter.create_emp_id
     *
     * @mbg.generated Wed Oct 24 00:12:40 CST 2018
     */
    public Integer getCreateEmpId() {
        return createEmpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_electric_meter.create_emp_id
     *
     * @param createEmpId the value for z_electric_meter.create_emp_id
     *
     * @mbg.generated Wed Oct 24 00:12:40 CST 2018
     */
    public void setCreateEmpId(Integer createEmpId) {
        this.createEmpId = createEmpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_electric_meter.create_emp
     *
     * @return the value of z_electric_meter.create_emp
     *
     * @mbg.generated Wed Oct 24 00:12:40 CST 2018
     */
    public String getCreateEmp() {
        return createEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_electric_meter.create_emp
     *
     * @param createEmp the value for z_electric_meter.create_emp
     *
     * @mbg.generated Wed Oct 24 00:12:40 CST 2018
     */
    public void setCreateEmp(String createEmp) {
        this.createEmp = createEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_electric_meter.modify_time
     *
     * @return the value of z_electric_meter.modify_time
     *
     * @mbg.generated Wed Oct 24 00:12:40 CST 2018
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_electric_meter.modify_time
     *
     * @param modifyTime the value for z_electric_meter.modify_time
     *
     * @mbg.generated Wed Oct 24 00:12:40 CST 2018
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_electric_meter.modify_emp_id
     *
     * @return the value of z_electric_meter.modify_emp_id
     *
     * @mbg.generated Wed Oct 24 00:12:40 CST 2018
     */
    public Integer getModifyEmpId() {
        return modifyEmpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_electric_meter.modify_emp_id
     *
     * @param modifyEmpId the value for z_electric_meter.modify_emp_id
     *
     * @mbg.generated Wed Oct 24 00:12:40 CST 2018
     */
    public void setModifyEmpId(Integer modifyEmpId) {
        this.modifyEmpId = modifyEmpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_electric_meter.modify_emp
     *
     * @return the value of z_electric_meter.modify_emp
     *
     * @mbg.generated Wed Oct 24 00:12:40 CST 2018
     */
    public String getModifyEmp() {
        return modifyEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_electric_meter.modify_emp
     *
     * @param modifyEmp the value for z_electric_meter.modify_emp
     *
     * @mbg.generated Wed Oct 24 00:12:40 CST 2018
     */
    public void setModifyEmp(String modifyEmp) {
        this.modifyEmp = modifyEmp;
    }
}