package cn.zxy.zmanager.dao.dataobject;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ZHouseFeeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table z_house_fee
     *
     * @mbg.generated Mon Oct 15 20:23:39 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table z_house_fee
     *
     * @mbg.generated Mon Oct 15 20:23:39 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table z_house_fee
     *
     * @mbg.generated Mon Oct 15 20:23:39 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_house_fee
     *
     * @mbg.generated Mon Oct 15 20:23:39 CST 2018
     */
    public ZHouseFeeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_house_fee
     *
     * @mbg.generated Mon Oct 15 20:23:39 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_house_fee
     *
     * @mbg.generated Mon Oct 15 20:23:39 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_house_fee
     *
     * @mbg.generated Mon Oct 15 20:23:39 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_house_fee
     *
     * @mbg.generated Mon Oct 15 20:23:39 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_house_fee
     *
     * @mbg.generated Mon Oct 15 20:23:39 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_house_fee
     *
     * @mbg.generated Mon Oct 15 20:23:39 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_house_fee
     *
     * @mbg.generated Mon Oct 15 20:23:39 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_house_fee
     *
     * @mbg.generated Mon Oct 15 20:23:39 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_house_fee
     *
     * @mbg.generated Mon Oct 15 20:23:39 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_house_fee
     *
     * @mbg.generated Mon Oct 15 20:23:39 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table z_house_fee
     *
     * @mbg.generated Mon Oct 15 20:23:39 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andContractHouseIdIsNull() {
            addCriterion("contract_house_id is null");
            return (Criteria) this;
        }

        public Criteria andContractHouseIdIsNotNull() {
            addCriterion("contract_house_id is not null");
            return (Criteria) this;
        }

        public Criteria andContractHouseIdEqualTo(Integer value) {
            addCriterion("contract_house_id =", value, "contractHouseId");
            return (Criteria) this;
        }

        public Criteria andContractHouseIdNotEqualTo(Integer value) {
            addCriterion("contract_house_id <>", value, "contractHouseId");
            return (Criteria) this;
        }

        public Criteria andContractHouseIdGreaterThan(Integer value) {
            addCriterion("contract_house_id >", value, "contractHouseId");
            return (Criteria) this;
        }

        public Criteria andContractHouseIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("contract_house_id >=", value, "contractHouseId");
            return (Criteria) this;
        }

        public Criteria andContractHouseIdLessThan(Integer value) {
            addCriterion("contract_house_id <", value, "contractHouseId");
            return (Criteria) this;
        }

        public Criteria andContractHouseIdLessThanOrEqualTo(Integer value) {
            addCriterion("contract_house_id <=", value, "contractHouseId");
            return (Criteria) this;
        }

        public Criteria andContractHouseIdIn(List<Integer> values) {
            addCriterion("contract_house_id in", values, "contractHouseId");
            return (Criteria) this;
        }

        public Criteria andContractHouseIdNotIn(List<Integer> values) {
            addCriterion("contract_house_id not in", values, "contractHouseId");
            return (Criteria) this;
        }

        public Criteria andContractHouseIdBetween(Integer value1, Integer value2) {
            addCriterion("contract_house_id between", value1, value2, "contractHouseId");
            return (Criteria) this;
        }

        public Criteria andContractHouseIdNotBetween(Integer value1, Integer value2) {
            addCriterion("contract_house_id not between", value1, value2, "contractHouseId");
            return (Criteria) this;
        }

        public Criteria andContractIdIsNull() {
            addCriterion("contract_id is null");
            return (Criteria) this;
        }

        public Criteria andContractIdIsNotNull() {
            addCriterion("contract_id is not null");
            return (Criteria) this;
        }

        public Criteria andContractIdEqualTo(Integer value) {
            addCriterion("contract_id =", value, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdNotEqualTo(Integer value) {
            addCriterion("contract_id <>", value, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdGreaterThan(Integer value) {
            addCriterion("contract_id >", value, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("contract_id >=", value, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdLessThan(Integer value) {
            addCriterion("contract_id <", value, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdLessThanOrEqualTo(Integer value) {
            addCriterion("contract_id <=", value, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdIn(List<Integer> values) {
            addCriterion("contract_id in", values, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdNotIn(List<Integer> values) {
            addCriterion("contract_id not in", values, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdBetween(Integer value1, Integer value2) {
            addCriterion("contract_id between", value1, value2, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdNotBetween(Integer value1, Integer value2) {
            addCriterion("contract_id not between", value1, value2, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractCodeIsNull() {
            addCriterion("contract_code is null");
            return (Criteria) this;
        }

        public Criteria andContractCodeIsNotNull() {
            addCriterion("contract_code is not null");
            return (Criteria) this;
        }

        public Criteria andContractCodeEqualTo(String value) {
            addCriterion("contract_code =", value, "contractCode");
            return (Criteria) this;
        }

        public Criteria andContractCodeNotEqualTo(String value) {
            addCriterion("contract_code <>", value, "contractCode");
            return (Criteria) this;
        }

        public Criteria andContractCodeGreaterThan(String value) {
            addCriterion("contract_code >", value, "contractCode");
            return (Criteria) this;
        }

        public Criteria andContractCodeGreaterThanOrEqualTo(String value) {
            addCriterion("contract_code >=", value, "contractCode");
            return (Criteria) this;
        }

        public Criteria andContractCodeLessThan(String value) {
            addCriterion("contract_code <", value, "contractCode");
            return (Criteria) this;
        }

        public Criteria andContractCodeLessThanOrEqualTo(String value) {
            addCriterion("contract_code <=", value, "contractCode");
            return (Criteria) this;
        }

        public Criteria andContractCodeLike(String value) {
            addCriterion("contract_code like", value, "contractCode");
            return (Criteria) this;
        }

        public Criteria andContractCodeNotLike(String value) {
            addCriterion("contract_code not like", value, "contractCode");
            return (Criteria) this;
        }

        public Criteria andContractCodeIn(List<String> values) {
            addCriterion("contract_code in", values, "contractCode");
            return (Criteria) this;
        }

        public Criteria andContractCodeNotIn(List<String> values) {
            addCriterion("contract_code not in", values, "contractCode");
            return (Criteria) this;
        }

        public Criteria andContractCodeBetween(String value1, String value2) {
            addCriterion("contract_code between", value1, value2, "contractCode");
            return (Criteria) this;
        }

        public Criteria andContractCodeNotBetween(String value1, String value2) {
            addCriterion("contract_code not between", value1, value2, "contractCode");
            return (Criteria) this;
        }

        public Criteria andHouseIdIsNull() {
            addCriterion("house_id is null");
            return (Criteria) this;
        }

        public Criteria andHouseIdIsNotNull() {
            addCriterion("house_id is not null");
            return (Criteria) this;
        }

        public Criteria andHouseIdEqualTo(Integer value) {
            addCriterion("house_id =", value, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdNotEqualTo(Integer value) {
            addCriterion("house_id <>", value, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdGreaterThan(Integer value) {
            addCriterion("house_id >", value, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("house_id >=", value, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdLessThan(Integer value) {
            addCriterion("house_id <", value, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdLessThanOrEqualTo(Integer value) {
            addCriterion("house_id <=", value, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdIn(List<Integer> values) {
            addCriterion("house_id in", values, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdNotIn(List<Integer> values) {
            addCriterion("house_id not in", values, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdBetween(Integer value1, Integer value2) {
            addCriterion("house_id between", value1, value2, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdNotBetween(Integer value1, Integer value2) {
            addCriterion("house_id not between", value1, value2, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseCodeIsNull() {
            addCriterion("house_code is null");
            return (Criteria) this;
        }

        public Criteria andHouseCodeIsNotNull() {
            addCriterion("house_code is not null");
            return (Criteria) this;
        }

        public Criteria andHouseCodeEqualTo(String value) {
            addCriterion("house_code =", value, "houseCode");
            return (Criteria) this;
        }

        public Criteria andHouseCodeNotEqualTo(String value) {
            addCriterion("house_code <>", value, "houseCode");
            return (Criteria) this;
        }

        public Criteria andHouseCodeGreaterThan(String value) {
            addCriterion("house_code >", value, "houseCode");
            return (Criteria) this;
        }

        public Criteria andHouseCodeGreaterThanOrEqualTo(String value) {
            addCriterion("house_code >=", value, "houseCode");
            return (Criteria) this;
        }

        public Criteria andHouseCodeLessThan(String value) {
            addCriterion("house_code <", value, "houseCode");
            return (Criteria) this;
        }

        public Criteria andHouseCodeLessThanOrEqualTo(String value) {
            addCriterion("house_code <=", value, "houseCode");
            return (Criteria) this;
        }

        public Criteria andHouseCodeLike(String value) {
            addCriterion("house_code like", value, "houseCode");
            return (Criteria) this;
        }

        public Criteria andHouseCodeNotLike(String value) {
            addCriterion("house_code not like", value, "houseCode");
            return (Criteria) this;
        }

        public Criteria andHouseCodeIn(List<String> values) {
            addCriterion("house_code in", values, "houseCode");
            return (Criteria) this;
        }

        public Criteria andHouseCodeNotIn(List<String> values) {
            addCriterion("house_code not in", values, "houseCode");
            return (Criteria) this;
        }

        public Criteria andHouseCodeBetween(String value1, String value2) {
            addCriterion("house_code between", value1, value2, "houseCode");
            return (Criteria) this;
        }

        public Criteria andHouseCodeNotBetween(String value1, String value2) {
            addCriterion("house_code not between", value1, value2, "houseCode");
            return (Criteria) this;
        }

        public Criteria andMerchantIdIsNull() {
            addCriterion("merchant_id is null");
            return (Criteria) this;
        }

        public Criteria andMerchantIdIsNotNull() {
            addCriterion("merchant_id is not null");
            return (Criteria) this;
        }

        public Criteria andMerchantIdEqualTo(Integer value) {
            addCriterion("merchant_id =", value, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdNotEqualTo(Integer value) {
            addCriterion("merchant_id <>", value, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdGreaterThan(Integer value) {
            addCriterion("merchant_id >", value, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("merchant_id >=", value, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdLessThan(Integer value) {
            addCriterion("merchant_id <", value, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdLessThanOrEqualTo(Integer value) {
            addCriterion("merchant_id <=", value, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdIn(List<Integer> values) {
            addCriterion("merchant_id in", values, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdNotIn(List<Integer> values) {
            addCriterion("merchant_id not in", values, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdBetween(Integer value1, Integer value2) {
            addCriterion("merchant_id between", value1, value2, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdNotBetween(Integer value1, Integer value2) {
            addCriterion("merchant_id not between", value1, value2, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantCodeIsNull() {
            addCriterion("merchant_code is null");
            return (Criteria) this;
        }

        public Criteria andMerchantCodeIsNotNull() {
            addCriterion("merchant_code is not null");
            return (Criteria) this;
        }

        public Criteria andMerchantCodeEqualTo(String value) {
            addCriterion("merchant_code =", value, "merchantCode");
            return (Criteria) this;
        }

        public Criteria andMerchantCodeNotEqualTo(String value) {
            addCriterion("merchant_code <>", value, "merchantCode");
            return (Criteria) this;
        }

        public Criteria andMerchantCodeGreaterThan(String value) {
            addCriterion("merchant_code >", value, "merchantCode");
            return (Criteria) this;
        }

        public Criteria andMerchantCodeGreaterThanOrEqualTo(String value) {
            addCriterion("merchant_code >=", value, "merchantCode");
            return (Criteria) this;
        }

        public Criteria andMerchantCodeLessThan(String value) {
            addCriterion("merchant_code <", value, "merchantCode");
            return (Criteria) this;
        }

        public Criteria andMerchantCodeLessThanOrEqualTo(String value) {
            addCriterion("merchant_code <=", value, "merchantCode");
            return (Criteria) this;
        }

        public Criteria andMerchantCodeLike(String value) {
            addCriterion("merchant_code like", value, "merchantCode");
            return (Criteria) this;
        }

        public Criteria andMerchantCodeNotLike(String value) {
            addCriterion("merchant_code not like", value, "merchantCode");
            return (Criteria) this;
        }

        public Criteria andMerchantCodeIn(List<String> values) {
            addCriterion("merchant_code in", values, "merchantCode");
            return (Criteria) this;
        }

        public Criteria andMerchantCodeNotIn(List<String> values) {
            addCriterion("merchant_code not in", values, "merchantCode");
            return (Criteria) this;
        }

        public Criteria andMerchantCodeBetween(String value1, String value2) {
            addCriterion("merchant_code between", value1, value2, "merchantCode");
            return (Criteria) this;
        }

        public Criteria andMerchantCodeNotBetween(String value1, String value2) {
            addCriterion("merchant_code not between", value1, value2, "merchantCode");
            return (Criteria) this;
        }

        public Criteria andCompanyIsNull() {
            addCriterion("company is null");
            return (Criteria) this;
        }

        public Criteria andCompanyIsNotNull() {
            addCriterion("company is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyEqualTo(String value) {
            addCriterion("company =", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyNotEqualTo(String value) {
            addCriterion("company <>", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyGreaterThan(String value) {
            addCriterion("company >", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyGreaterThanOrEqualTo(String value) {
            addCriterion("company >=", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyLessThan(String value) {
            addCriterion("company <", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyLessThanOrEqualTo(String value) {
            addCriterion("company <=", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyLike(String value) {
            addCriterion("company like", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyNotLike(String value) {
            addCriterion("company not like", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyIn(List<String> values) {
            addCriterion("company in", values, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyNotIn(List<String> values) {
            addCriterion("company not in", values, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyBetween(String value1, String value2) {
            addCriterion("company between", value1, value2, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyNotBetween(String value1, String value2) {
            addCriterion("company not between", value1, value2, "company");
            return (Criteria) this;
        }

        public Criteria andCorporateBodyIsNull() {
            addCriterion("corporate_body is null");
            return (Criteria) this;
        }

        public Criteria andCorporateBodyIsNotNull() {
            addCriterion("corporate_body is not null");
            return (Criteria) this;
        }

        public Criteria andCorporateBodyEqualTo(String value) {
            addCriterion("corporate_body =", value, "corporateBody");
            return (Criteria) this;
        }

        public Criteria andCorporateBodyNotEqualTo(String value) {
            addCriterion("corporate_body <>", value, "corporateBody");
            return (Criteria) this;
        }

        public Criteria andCorporateBodyGreaterThan(String value) {
            addCriterion("corporate_body >", value, "corporateBody");
            return (Criteria) this;
        }

        public Criteria andCorporateBodyGreaterThanOrEqualTo(String value) {
            addCriterion("corporate_body >=", value, "corporateBody");
            return (Criteria) this;
        }

        public Criteria andCorporateBodyLessThan(String value) {
            addCriterion("corporate_body <", value, "corporateBody");
            return (Criteria) this;
        }

        public Criteria andCorporateBodyLessThanOrEqualTo(String value) {
            addCriterion("corporate_body <=", value, "corporateBody");
            return (Criteria) this;
        }

        public Criteria andCorporateBodyLike(String value) {
            addCriterion("corporate_body like", value, "corporateBody");
            return (Criteria) this;
        }

        public Criteria andCorporateBodyNotLike(String value) {
            addCriterion("corporate_body not like", value, "corporateBody");
            return (Criteria) this;
        }

        public Criteria andCorporateBodyIn(List<String> values) {
            addCriterion("corporate_body in", values, "corporateBody");
            return (Criteria) this;
        }

        public Criteria andCorporateBodyNotIn(List<String> values) {
            addCriterion("corporate_body not in", values, "corporateBody");
            return (Criteria) this;
        }

        public Criteria andCorporateBodyBetween(String value1, String value2) {
            addCriterion("corporate_body between", value1, value2, "corporateBody");
            return (Criteria) this;
        }

        public Criteria andCorporateBodyNotBetween(String value1, String value2) {
            addCriterion("corporate_body not between", value1, value2, "corporateBody");
            return (Criteria) this;
        }

        public Criteria andRentFeeIsNull() {
            addCriterion("rent_fee is null");
            return (Criteria) this;
        }

        public Criteria andRentFeeIsNotNull() {
            addCriterion("rent_fee is not null");
            return (Criteria) this;
        }

        public Criteria andRentFeeEqualTo(Integer value) {
            addCriterion("rent_fee =", value, "rentFee");
            return (Criteria) this;
        }

        public Criteria andRentFeeNotEqualTo(Integer value) {
            addCriterion("rent_fee <>", value, "rentFee");
            return (Criteria) this;
        }

        public Criteria andRentFeeGreaterThan(Integer value) {
            addCriterion("rent_fee >", value, "rentFee");
            return (Criteria) this;
        }

        public Criteria andRentFeeGreaterThanOrEqualTo(Integer value) {
            addCriterion("rent_fee >=", value, "rentFee");
            return (Criteria) this;
        }

        public Criteria andRentFeeLessThan(Integer value) {
            addCriterion("rent_fee <", value, "rentFee");
            return (Criteria) this;
        }

        public Criteria andRentFeeLessThanOrEqualTo(Integer value) {
            addCriterion("rent_fee <=", value, "rentFee");
            return (Criteria) this;
        }

        public Criteria andRentFeeIn(List<Integer> values) {
            addCriterion("rent_fee in", values, "rentFee");
            return (Criteria) this;
        }

        public Criteria andRentFeeNotIn(List<Integer> values) {
            addCriterion("rent_fee not in", values, "rentFee");
            return (Criteria) this;
        }

        public Criteria andRentFeeBetween(Integer value1, Integer value2) {
            addCriterion("rent_fee between", value1, value2, "rentFee");
            return (Criteria) this;
        }

        public Criteria andRentFeeNotBetween(Integer value1, Integer value2) {
            addCriterion("rent_fee not between", value1, value2, "rentFee");
            return (Criteria) this;
        }

        public Criteria andPropertyFeeIsNull() {
            addCriterion("property_fee is null");
            return (Criteria) this;
        }

        public Criteria andPropertyFeeIsNotNull() {
            addCriterion("property_fee is not null");
            return (Criteria) this;
        }

        public Criteria andPropertyFeeEqualTo(Integer value) {
            addCriterion("property_fee =", value, "propertyFee");
            return (Criteria) this;
        }

        public Criteria andPropertyFeeNotEqualTo(Integer value) {
            addCriterion("property_fee <>", value, "propertyFee");
            return (Criteria) this;
        }

        public Criteria andPropertyFeeGreaterThan(Integer value) {
            addCriterion("property_fee >", value, "propertyFee");
            return (Criteria) this;
        }

        public Criteria andPropertyFeeGreaterThanOrEqualTo(Integer value) {
            addCriterion("property_fee >=", value, "propertyFee");
            return (Criteria) this;
        }

        public Criteria andPropertyFeeLessThan(Integer value) {
            addCriterion("property_fee <", value, "propertyFee");
            return (Criteria) this;
        }

        public Criteria andPropertyFeeLessThanOrEqualTo(Integer value) {
            addCriterion("property_fee <=", value, "propertyFee");
            return (Criteria) this;
        }

        public Criteria andPropertyFeeIn(List<Integer> values) {
            addCriterion("property_fee in", values, "propertyFee");
            return (Criteria) this;
        }

        public Criteria andPropertyFeeNotIn(List<Integer> values) {
            addCriterion("property_fee not in", values, "propertyFee");
            return (Criteria) this;
        }

        public Criteria andPropertyFeeBetween(Integer value1, Integer value2) {
            addCriterion("property_fee between", value1, value2, "propertyFee");
            return (Criteria) this;
        }

        public Criteria andPropertyFeeNotBetween(Integer value1, Integer value2) {
            addCriterion("property_fee not between", value1, value2, "propertyFee");
            return (Criteria) this;
        }

        public Criteria andAreaIsNull() {
            addCriterion("area is null");
            return (Criteria) this;
        }

        public Criteria andAreaIsNotNull() {
            addCriterion("area is not null");
            return (Criteria) this;
        }

        public Criteria andAreaEqualTo(Double value) {
            addCriterion("area =", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotEqualTo(Double value) {
            addCriterion("area <>", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaGreaterThan(Double value) {
            addCriterion("area >", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaGreaterThanOrEqualTo(Double value) {
            addCriterion("area >=", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaLessThan(Double value) {
            addCriterion("area <", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaLessThanOrEqualTo(Double value) {
            addCriterion("area <=", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaIn(List<Double> values) {
            addCriterion("area in", values, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotIn(List<Double> values) {
            addCriterion("area not in", values, "area");
            return (Criteria) this;
        }

        public Criteria andAreaBetween(Double value1, Double value2) {
            addCriterion("area between", value1, value2, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotBetween(Double value1, Double value2) {
            addCriterion("area not between", value1, value2, "area");
            return (Criteria) this;
        }

        public Criteria andSortIsNull() {
            addCriterion("sort is null");
            return (Criteria) this;
        }

        public Criteria andSortIsNotNull() {
            addCriterion("sort is not null");
            return (Criteria) this;
        }

        public Criteria andSortEqualTo(Integer value) {
            addCriterion("sort =", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortNotEqualTo(Integer value) {
            addCriterion("sort <>", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortGreaterThan(Integer value) {
            addCriterion("sort >", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortGreaterThanOrEqualTo(Integer value) {
            addCriterion("sort >=", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortLessThan(Integer value) {
            addCriterion("sort <", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortLessThanOrEqualTo(Integer value) {
            addCriterion("sort <=", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortIn(List<Integer> values) {
            addCriterion("sort in", values, "sort");
            return (Criteria) this;
        }

        public Criteria andSortNotIn(List<Integer> values) {
            addCriterion("sort not in", values, "sort");
            return (Criteria) this;
        }

        public Criteria andSortBetween(Integer value1, Integer value2) {
            addCriterion("sort between", value1, value2, "sort");
            return (Criteria) this;
        }

        public Criteria andSortNotBetween(Integer value1, Integer value2) {
            addCriterion("sort not between", value1, value2, "sort");
            return (Criteria) this;
        }

        public Criteria andTotalRentFeeIsNull() {
            addCriterion("total_rent_fee is null");
            return (Criteria) this;
        }

        public Criteria andTotalRentFeeIsNotNull() {
            addCriterion("total_rent_fee is not null");
            return (Criteria) this;
        }

        public Criteria andTotalRentFeeEqualTo(Integer value) {
            addCriterion("total_rent_fee =", value, "totalRentFee");
            return (Criteria) this;
        }

        public Criteria andTotalRentFeeNotEqualTo(Integer value) {
            addCriterion("total_rent_fee <>", value, "totalRentFee");
            return (Criteria) this;
        }

        public Criteria andTotalRentFeeGreaterThan(Integer value) {
            addCriterion("total_rent_fee >", value, "totalRentFee");
            return (Criteria) this;
        }

        public Criteria andTotalRentFeeGreaterThanOrEqualTo(Integer value) {
            addCriterion("total_rent_fee >=", value, "totalRentFee");
            return (Criteria) this;
        }

        public Criteria andTotalRentFeeLessThan(Integer value) {
            addCriterion("total_rent_fee <", value, "totalRentFee");
            return (Criteria) this;
        }

        public Criteria andTotalRentFeeLessThanOrEqualTo(Integer value) {
            addCriterion("total_rent_fee <=", value, "totalRentFee");
            return (Criteria) this;
        }

        public Criteria andTotalRentFeeIn(List<Integer> values) {
            addCriterion("total_rent_fee in", values, "totalRentFee");
            return (Criteria) this;
        }

        public Criteria andTotalRentFeeNotIn(List<Double> values) {
            addCriterion("total_rent_fee not in", values, "totalRentFee");
            return (Criteria) this;
        }

        public Criteria andTotalRentFeeBetween(Integer value1, Integer value2) {
            addCriterion("total_rent_fee between", value1, value2, "totalRentFee");
            return (Criteria) this;
        }

        public Criteria andTotalRentFeeNotBetween(Integer value1, Integer value2) {
            addCriterion("total_rent_fee not between", value1, value2, "totalRentFee");
            return (Criteria) this;
        }

        public Criteria andTotalPropertyFeeIsNull() {
            addCriterion("total_property_fee is null");
            return (Criteria) this;
        }

        public Criteria andTotalPropertyFeeIsNotNull() {
            addCriterion("total_property_fee is not null");
            return (Criteria) this;
        }

        public Criteria andTotalPropertyFeeEqualTo(Integer value) {
            addCriterion("total_property_fee =", value, "totalPropertyFee");
            return (Criteria) this;
        }

        public Criteria andTotalPropertyFeeNotEqualTo(Integer value) {
            addCriterion("total_property_fee <>", value, "totalPropertyFee");
            return (Criteria) this;
        }

        public Criteria andTotalPropertyFeeGreaterThan(Integer value) {
            addCriterion("total_property_fee >", value, "totalPropertyFee");
            return (Criteria) this;
        }

        public Criteria andTotalPropertyFeeGreaterThanOrEqualTo(Integer value) {
            addCriterion("total_property_fee >=", value, "totalPropertyFee");
            return (Criteria) this;
        }

        public Criteria andTotalPropertyFeeLessThan(Integer value) {
            addCriterion("total_property_fee <", value, "totalPropertyFee");
            return (Criteria) this;
        }

        public Criteria andTotalPropertyFeeLessThanOrEqualTo(Integer value) {
            addCriterion("total_property_fee <=", value, "totalPropertyFee");
            return (Criteria) this;
        }

        public Criteria andTotalPropertyFeeIn(List<Integer> values) {
            addCriterion("total_property_fee in", values, "totalPropertyFee");
            return (Criteria) this;
        }

        public Criteria andTotalPropertyFeeNotIn(List<Integer> values) {
            addCriterion("total_property_fee not in", values, "totalPropertyFee");
            return (Criteria) this;
        }

        public Criteria andTotalPropertyFeeBetween(Integer value1, Integer value2) {
            addCriterion("total_property_fee between", value1, value2, "totalPropertyFee");
            return (Criteria) this;
        }

        public Criteria andTotalPropertyFeeNotBetween(Integer value1, Integer value2) {
            addCriterion("total_property_fee not between", value1, value2, "totalPropertyFee");
            return (Criteria) this;
        }

        public Criteria andRentMonthIsNull() {
            addCriterion("rent_month is null");
            return (Criteria) this;
        }

        public Criteria andRentMonthIsNotNull() {
            addCriterion("rent_month is not null");
            return (Criteria) this;
        }

        public Criteria andRentMonthEqualTo(Integer value) {
            addCriterion("rent_month =", value, "rentMonth");
            return (Criteria) this;
        }

        public Criteria andRentMonthNotEqualTo(Integer value) {
            addCriterion("rent_month <>", value, "rentMonth");
            return (Criteria) this;
        }

        public Criteria andRentMonthGreaterThan(Integer value) {
            addCriterion("rent_month >", value, "rentMonth");
            return (Criteria) this;
        }

        public Criteria andRentMonthGreaterThanOrEqualTo(Integer value) {
            addCriterion("rent_month >=", value, "rentMonth");
            return (Criteria) this;
        }

        public Criteria andRentMonthLessThan(Integer value) {
            addCriterion("rent_month <", value, "rentMonth");
            return (Criteria) this;
        }

        public Criteria andRentMonthLessThanOrEqualTo(Integer value) {
            addCriterion("rent_month <=", value, "rentMonth");
            return (Criteria) this;
        }

        public Criteria andRentMonthIn(List<Integer> values) {
            addCriterion("rent_month in", values, "rentMonth");
            return (Criteria) this;
        }

        public Criteria andRentMonthNotIn(List<Integer> values) {
            addCriterion("rent_month not in", values, "rentMonth");
            return (Criteria) this;
        }

        public Criteria andRentMonthBetween(Integer value1, Integer value2) {
            addCriterion("rent_month between", value1, value2, "rentMonth");
            return (Criteria) this;
        }

        public Criteria andRentMonthNotBetween(Integer value1, Integer value2) {
            addCriterion("rent_month not between", value1, value2, "rentMonth");
            return (Criteria) this;
        }

        public Criteria andPropertyMonthIsNull() {
            addCriterion("property_month is null");
            return (Criteria) this;
        }

        public Criteria andPropertyMonthIsNotNull() {
            addCriterion("property_month is not null");
            return (Criteria) this;
        }

        public Criteria andPropertyMonthEqualTo(Integer value) {
            addCriterion("property_month =", value, "propertyMonth");
            return (Criteria) this;
        }

        public Criteria andPropertyMonthNotEqualTo(Integer value) {
            addCriterion("property_month <>", value, "propertyMonth");
            return (Criteria) this;
        }

        public Criteria andPropertyMonthGreaterThan(Integer value) {
            addCriterion("property_month >", value, "propertyMonth");
            return (Criteria) this;
        }

        public Criteria andPropertyMonthGreaterThanOrEqualTo(Integer value) {
            addCriterion("property_month >=", value, "propertyMonth");
            return (Criteria) this;
        }

        public Criteria andPropertyMonthLessThan(Integer value) {
            addCriterion("property_month <", value, "propertyMonth");
            return (Criteria) this;
        }

        public Criteria andPropertyMonthLessThanOrEqualTo(Integer value) {
            addCriterion("property_month <=", value, "propertyMonth");
            return (Criteria) this;
        }

        public Criteria andPropertyMonthIn(List<Integer> values) {
            addCriterion("property_month in", values, "propertyMonth");
            return (Criteria) this;
        }

        public Criteria andPropertyMonthNotIn(List<Integer> values) {
            addCriterion("property_month not in", values, "propertyMonth");
            return (Criteria) this;
        }

        public Criteria andPropertyMonthBetween(Integer value1, Integer value2) {
            addCriterion("property_month between", value1, value2, "propertyMonth");
            return (Criteria) this;
        }

        public Criteria andPropertyMonthNotBetween(Integer value1, Integer value2) {
            addCriterion("property_month not between", value1, value2, "propertyMonth");
            return (Criteria) this;
        }

        public Criteria andPayDeadlineIsNull() {
            addCriterion("pay_deadline is null");
            return (Criteria) this;
        }

        public Criteria andPayDeadlineIsNotNull() {
            addCriterion("pay_deadline is not null");
            return (Criteria) this;
        }

        public Criteria andPayDeadlineEqualTo(Date value) {
            addCriterion("pay_deadline =", value, "payDeadline");
            return (Criteria) this;
        }

        public Criteria andPayDeadlineNotEqualTo(Date value) {
            addCriterion("pay_deadline <>", value, "payDeadline");
            return (Criteria) this;
        }

        public Criteria andPayDeadlineGreaterThan(Date value) {
            addCriterion("pay_deadline >", value, "payDeadline");
            return (Criteria) this;
        }

        public Criteria andPayDeadlineGreaterThanOrEqualTo(Date value) {
            addCriterion("pay_deadline >=", value, "payDeadline");
            return (Criteria) this;
        }

        public Criteria andPayDeadlineLessThan(Date value) {
            addCriterion("pay_deadline <", value, "payDeadline");
            return (Criteria) this;
        }

        public Criteria andPayDeadlineLessThanOrEqualTo(Date value) {
            addCriterion("pay_deadline <=", value, "payDeadline");
            return (Criteria) this;
        }

        public Criteria andPayDeadlineIn(List<Date> values) {
            addCriterion("pay_deadline in", values, "payDeadline");
            return (Criteria) this;
        }

        public Criteria andPayDeadlineNotIn(List<Date> values) {
            addCriterion("pay_deadline not in", values, "payDeadline");
            return (Criteria) this;
        }

        public Criteria andPayDeadlineBetween(Date value1, Date value2) {
            addCriterion("pay_deadline between", value1, value2, "payDeadline");
            return (Criteria) this;
        }

        public Criteria andPayDeadlineNotBetween(Date value1, Date value2) {
            addCriterion("pay_deadline not between", value1, value2, "payDeadline");
            return (Criteria) this;
        }

        public Criteria andRemarksIsNull() {
            addCriterion("remarks is null");
            return (Criteria) this;
        }

        public Criteria andRemarksIsNotNull() {
            addCriterion("remarks is not null");
            return (Criteria) this;
        }

        public Criteria andRemarksEqualTo(String value) {
            addCriterion("remarks =", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotEqualTo(String value) {
            addCriterion("remarks <>", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksGreaterThan(String value) {
            addCriterion("remarks >", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksGreaterThanOrEqualTo(String value) {
            addCriterion("remarks >=", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLessThan(String value) {
            addCriterion("remarks <", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLessThanOrEqualTo(String value) {
            addCriterion("remarks <=", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLike(String value) {
            addCriterion("remarks like", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotLike(String value) {
            addCriterion("remarks not like", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksIn(List<String> values) {
            addCriterion("remarks in", values, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotIn(List<String> values) {
            addCriterion("remarks not in", values, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksBetween(String value1, String value2) {
            addCriterion("remarks between", value1, value2, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotBetween(String value1, String value2) {
            addCriterion("remarks not between", value1, value2, "remarks");
            return (Criteria) this;
        }

        public Criteria andPaidRentFeeIsNull() {
            addCriterion("paid_rent_fee is null");
            return (Criteria) this;
        }

        public Criteria andPaidRentFeeIsNotNull() {
            addCriterion("paid_rent_fee is not null");
            return (Criteria) this;
        }

        public Criteria andPaidRentFeeEqualTo(Integer value) {
            addCriterion("paid_rent_fee =", value, "paidRentFee");
            return (Criteria) this;
        }

        public Criteria andPaidRentFeeNotEqualTo(Integer value) {
            addCriterion("paid_rent_fee <>", value, "paidRentFee");
            return (Criteria) this;
        }

        public Criteria andPaidRentFeeGreaterThan(Integer value) {
            addCriterion("paid_rent_fee >", value, "paidRentFee");
            return (Criteria) this;
        }

        public Criteria andPaidRentFeeGreaterThanOrEqualTo(Integer value) {
            addCriterion("paid_rent_fee >=", value, "paidRentFee");
            return (Criteria) this;
        }

        public Criteria andPaidRentFeeLessThan(Integer value) {
            addCriterion("paid_rent_fee <", value, "paidRentFee");
            return (Criteria) this;
        }

        public Criteria andPaidRentFeeLessThanOrEqualTo(Integer value) {
            addCriterion("paid_rent_fee <=", value, "paidRentFee");
            return (Criteria) this;
        }

        public Criteria andPaidRentFeeIn(List<Integer> values) {
            addCriterion("paid_rent_fee in", values, "paidRentFee");
            return (Criteria) this;
        }

        public Criteria andPaidRentFeeNotIn(List<Integer> values) {
            addCriterion("paid_rent_fee not in", values, "paidRentFee");
            return (Criteria) this;
        }

        public Criteria andPaidRentFeeBetween(Integer value1, Integer value2) {
            addCriterion("paid_rent_fee between", value1, value2, "paidRentFee");
            return (Criteria) this;
        }

        public Criteria andPaidRentFeeNotBetween(Integer value1, Integer value2) {
            addCriterion("paid_rent_fee not between", value1, value2, "paidRentFee");
            return (Criteria) this;
        }

        public Criteria andPaidPropertyFeeIsNull() {
            addCriterion("paid_property_fee is null");
            return (Criteria) this;
        }

        public Criteria andPaidPropertyFeeIsNotNull() {
            addCriterion("paid_property_fee is not null");
            return (Criteria) this;
        }

        public Criteria andPaidPropertyFeeEqualTo(Integer value) {
            addCriterion("paid_property_fee =", value, "paidPropertyFee");
            return (Criteria) this;
        }

        public Criteria andPaidPropertyFeeNotEqualTo(Integer value) {
            addCriterion("paid_property_fee <>", value, "paidPropertyFee");
            return (Criteria) this;
        }

        public Criteria andPaidPropertyFeeGreaterThan(Integer value) {
            addCriterion("paid_property_fee >", value, "paidPropertyFee");
            return (Criteria) this;
        }

        public Criteria andPaidPropertyFeeGreaterThanOrEqualTo(Integer value) {
            addCriterion("paid_property_fee >=", value, "paidPropertyFee");
            return (Criteria) this;
        }

        public Criteria andPaidPropertyFeeLessThan(Integer value) {
            addCriterion("paid_property_fee <", value, "paidPropertyFee");
            return (Criteria) this;
        }

        public Criteria andPaidPropertyFeeLessThanOrEqualTo(Integer value) {
            addCriterion("paid_property_fee <=", value, "paidPropertyFee");
            return (Criteria) this;
        }

        public Criteria andPaidPropertyFeeIn(List<Integer> values) {
            addCriterion("paid_property_fee in", values, "paidPropertyFee");
            return (Criteria) this;
        }

        public Criteria andPaidPropertyFeeNotIn(List<Integer> values) {
            addCriterion("paid_property_fee not in", values, "paidPropertyFee");
            return (Criteria) this;
        }

        public Criteria andPaidPropertyFeeBetween(Integer value1, Integer value2) {
            addCriterion("paid_property_fee between", value1, value2, "paidPropertyFee");
            return (Criteria) this;
        }

        public Criteria andPaidPropertyFeeNotBetween(Integer value1, Integer value2) {
            addCriterion("paid_property_fee not between", value1, value2, "paidPropertyFee");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table z_house_fee
     *
     * @mbg.generated do_not_delete_during_merge Mon Oct 15 20:23:39 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table z_house_fee
     *
     * @mbg.generated Mon Oct 15 20:23:39 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}