package cn.zxy.zmanager.dao.dataobject;

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;

public class ZMaterial {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_material.id
     *
     * @mbg.generated Fri Nov 09 22:52:15 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_material.type
     *
     * @mbg.generated Fri Nov 09 22:52:15 CST 2018
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_material.name
     *
     * @mbg.generated Fri Nov 09 22:52:15 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_material.format
     *
     * @mbg.generated Fri Nov 09 22:52:15 CST 2018
     */
    private String format;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_material.stock_addr
     *
     * @mbg.generated Fri Nov 09 22:52:15 CST 2018
     */
    private String stockAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_material.stock_num
     *
     * @mbg.generated Fri Nov 09 22:52:15 CST 2018
     */
    private Integer stockNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_material.remarks
     *
     * @mbg.generated Fri Nov 09 22:52:15 CST 2018
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_material.create_emp
     *
     * @mbg.generated Fri Nov 09 22:52:15 CST 2018
     */
    private String createEmp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_material.create_emp_id
     *
     * @mbg.generated Fri Nov 09 22:52:15 CST 2018
     */
    private Integer createEmpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_material.create_time
     *
     * @mbg.generated Fri Nov 09 22:52:15 CST 2018
     */
    @JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_material.modify_emp
     *
     * @mbg.generated Fri Nov 09 22:52:15 CST 2018
     */
    private String modifyEmp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_material.modify_emp_id
     *
     * @mbg.generated Fri Nov 09 22:52:15 CST 2018
     */
    private Integer modifyEmpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_material.modify_time
     *
     * @mbg.generated Fri Nov 09 22:52:15 CST 2018
     */
    @JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_material.id
     *
     * @return the value of z_material.id
     *
     * @mbg.generated Fri Nov 09 22:52:15 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_material.id
     *
     * @param id the value for z_material.id
     *
     * @mbg.generated Fri Nov 09 22:52:15 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_material.type
     *
     * @return the value of z_material.type
     *
     * @mbg.generated Fri Nov 09 22:52:15 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_material.type
     *
     * @param type the value for z_material.type
     *
     * @mbg.generated Fri Nov 09 22:52:15 CST 2018
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_material.name
     *
     * @return the value of z_material.name
     *
     * @mbg.generated Fri Nov 09 22:52:15 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_material.name
     *
     * @param name the value for z_material.name
     *
     * @mbg.generated Fri Nov 09 22:52:15 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_material.format
     *
     * @return the value of z_material.format
     *
     * @mbg.generated Fri Nov 09 22:52:15 CST 2018
     */
    public String getFormat() {
        return format;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_material.format
     *
     * @param format the value for z_material.format
     *
     * @mbg.generated Fri Nov 09 22:52:15 CST 2018
     */
    public void setFormat(String format) {
        this.format = format;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_material.stock_addr
     *
     * @return the value of z_material.stock_addr
     *
     * @mbg.generated Fri Nov 09 22:52:15 CST 2018
     */
    public String getStockAddr() {
        return stockAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_material.stock_addr
     *
     * @param stockAddr the value for z_material.stock_addr
     *
     * @mbg.generated Fri Nov 09 22:52:15 CST 2018
     */
    public void setStockAddr(String stockAddr) {
        this.stockAddr = stockAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_material.stock_num
     *
     * @return the value of z_material.stock_num
     *
     * @mbg.generated Fri Nov 09 22:52:15 CST 2018
     */
    public Integer getStockNum() {
        return stockNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_material.stock_num
     *
     * @param stockNum the value for z_material.stock_num
     *
     * @mbg.generated Fri Nov 09 22:52:15 CST 2018
     */
    public void setStockNum(Integer stockNum) {
        this.stockNum = stockNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_material.remarks
     *
     * @return the value of z_material.remarks
     *
     * @mbg.generated Fri Nov 09 22:52:15 CST 2018
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_material.remarks
     *
     * @param remarks the value for z_material.remarks
     *
     * @mbg.generated Fri Nov 09 22:52:15 CST 2018
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_material.create_emp
     *
     * @return the value of z_material.create_emp
     *
     * @mbg.generated Fri Nov 09 22:52:15 CST 2018
     */
    public String getCreateEmp() {
        return createEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_material.create_emp
     *
     * @param createEmp the value for z_material.create_emp
     *
     * @mbg.generated Fri Nov 09 22:52:15 CST 2018
     */
    public void setCreateEmp(String createEmp) {
        this.createEmp = createEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_material.create_emp_id
     *
     * @return the value of z_material.create_emp_id
     *
     * @mbg.generated Fri Nov 09 22:52:15 CST 2018
     */
    public Integer getCreateEmpId() {
        return createEmpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_material.create_emp_id
     *
     * @param createEmpId the value for z_material.create_emp_id
     *
     * @mbg.generated Fri Nov 09 22:52:15 CST 2018
     */
    public void setCreateEmpId(Integer createEmpId) {
        this.createEmpId = createEmpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_material.create_time
     *
     * @return the value of z_material.create_time
     *
     * @mbg.generated Fri Nov 09 22:52:15 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_material.create_time
     *
     * @param createTime the value for z_material.create_time
     *
     * @mbg.generated Fri Nov 09 22:52:15 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_material.modify_emp
     *
     * @return the value of z_material.modify_emp
     *
     * @mbg.generated Fri Nov 09 22:52:15 CST 2018
     */
    public String getModifyEmp() {
        return modifyEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_material.modify_emp
     *
     * @param modifyEmp the value for z_material.modify_emp
     *
     * @mbg.generated Fri Nov 09 22:52:15 CST 2018
     */
    public void setModifyEmp(String modifyEmp) {
        this.modifyEmp = modifyEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_material.modify_emp_id
     *
     * @return the value of z_material.modify_emp_id
     *
     * @mbg.generated Fri Nov 09 22:52:15 CST 2018
     */
    public Integer getModifyEmpId() {
        return modifyEmpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_material.modify_emp_id
     *
     * @param modifyEmpId the value for z_material.modify_emp_id
     *
     * @mbg.generated Fri Nov 09 22:52:15 CST 2018
     */
    public void setModifyEmpId(Integer modifyEmpId) {
        this.modifyEmpId = modifyEmpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_material.modify_time
     *
     * @return the value of z_material.modify_time
     *
     * @mbg.generated Fri Nov 09 22:52:15 CST 2018
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_material.modify_time
     *
     * @param modifyTime the value for z_material.modify_time
     *
     * @mbg.generated Fri Nov 09 22:52:15 CST 2018
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}