package cn.zxy.zmanager.dao.dataobject;

import java.util.Date;

public class ZPaidFeeDetail {
	
	/** 收费类型：租金 */
	public static final Integer RENT_FEE = 0;
	
	/** 收费类型：物业费  */
	public static final Integer PROPERTY_FEE = 1;
	
	/** 收费类型：水费 */
	public static final Integer WATER_FEE = 2;
	
	/** 收费类型：电费 */
	public static final Integer ELECTRIC_FEE = 3;
	
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_paid_fee_detail.id
     *
     * @mbg.generated Sat Oct 27 16:31:40 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_paid_fee_detail.contract_code
     *
     * @mbg.generated Sat Oct 27 16:31:40 CST 2018
     */
    private String contractCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_paid_fee_detail.contract_id
     *
     * @mbg.generated Sat Oct 27 16:31:40 CST 2018
     */
    private Integer contractId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_paid_fee_detail.paid_fee
     *
     * @mbg.generated Sat Oct 27 16:31:40 CST 2018
     */
    private Integer paidFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_paid_fee_detail.paid_time
     *
     * @mbg.generated Sat Oct 27 16:31:40 CST 2018
     */
    private Date paidTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_paid_fee_detail.paid_method
     *
     * @mbg.generated Sat Oct 27 16:31:40 CST 2018
     */
    private Byte paidMethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_paid_fee_detail.electric
     *
     * @mbg.generated Sat Oct 27 16:31:40 CST 2018
     */
    private Integer electric;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_paid_fee_detail.paid_man
     *
     * @mbg.generated Sat Oct 27 16:31:40 CST 2018
     */
    private String paidMan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_paid_fee_detail.charge_man
     *
     * @mbg.generated Sat Oct 27 16:31:40 CST 2018
     */
    private String chargeMan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_paid_fee_detail.remarks
     *
     * @mbg.generated Sat Oct 27 16:31:40 CST 2018
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_paid_fee_detail.fee_type
     *
     * @mbg.generated Sat Oct 27 16:31:40 CST 2018
     */
    private Boolean feeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_paid_fee_detail.status
     *
     * @mbg.generated Sat Oct 27 16:31:40 CST 2018
     */
    private Boolean status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_paid_fee_detail.create_emp_id
     *
     * @mbg.generated Sat Oct 27 16:31:40 CST 2018
     */
    private Integer createEmpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_paid_fee_detail.create_emp
     *
     * @mbg.generated Sat Oct 27 16:31:40 CST 2018
     */
    private String createEmp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_paid_fee_detail.create_time
     *
     * @mbg.generated Sat Oct 27 16:31:40 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_paid_fee_detail.modify_emp_id
     *
     * @mbg.generated Sat Oct 27 16:31:40 CST 2018
     */
    private Integer modifyEmpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_paid_fee_detail.modify_emp
     *
     * @mbg.generated Sat Oct 27 16:31:40 CST 2018
     */
    private String modifyEmp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_paid_fee_detail.modify_time
     *
     * @mbg.generated Sat Oct 27 16:31:40 CST 2018
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_paid_fee_detail.id
     *
     * @return the value of z_paid_fee_detail.id
     *
     * @mbg.generated Sat Oct 27 16:31:40 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_paid_fee_detail.id
     *
     * @param id the value for z_paid_fee_detail.id
     *
     * @mbg.generated Sat Oct 27 16:31:40 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_paid_fee_detail.contract_code
     *
     * @return the value of z_paid_fee_detail.contract_code
     *
     * @mbg.generated Sat Oct 27 16:31:40 CST 2018
     */
    public String getContractCode() {
        return contractCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_paid_fee_detail.contract_code
     *
     * @param contractCode the value for z_paid_fee_detail.contract_code
     *
     * @mbg.generated Sat Oct 27 16:31:40 CST 2018
     */
    public void setContractCode(String contractCode) {
        this.contractCode = contractCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_paid_fee_detail.contract_id
     *
     * @return the value of z_paid_fee_detail.contract_id
     *
     * @mbg.generated Sat Oct 27 16:31:40 CST 2018
     */
    public Integer getContractId() {
        return contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_paid_fee_detail.contract_id
     *
     * @param contractId the value for z_paid_fee_detail.contract_id
     *
     * @mbg.generated Sat Oct 27 16:31:40 CST 2018
     */
    public void setContractId(Integer contractId) {
        this.contractId = contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_paid_fee_detail.paid_fee
     *
     * @return the value of z_paid_fee_detail.paid_fee
     *
     * @mbg.generated Sat Oct 27 16:31:40 CST 2018
     */
    public Integer getPaidFee() {
        return paidFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_paid_fee_detail.paid_fee
     *
     * @param paidFee the value for z_paid_fee_detail.paid_fee
     *
     * @mbg.generated Sat Oct 27 16:31:40 CST 2018
     */
    public void setPaidFee(Integer paidFee) {
        this.paidFee = paidFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_paid_fee_detail.paid_time
     *
     * @return the value of z_paid_fee_detail.paid_time
     *
     * @mbg.generated Sat Oct 27 16:31:40 CST 2018
     */
    public Date getPaidTime() {
        return paidTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_paid_fee_detail.paid_time
     *
     * @param paidTime the value for z_paid_fee_detail.paid_time
     *
     * @mbg.generated Sat Oct 27 16:31:40 CST 2018
     */
    public void setPaidTime(Date paidTime) {
        this.paidTime = paidTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_paid_fee_detail.paid_method
     *
     * @return the value of z_paid_fee_detail.paid_method
     *
     * @mbg.generated Sat Oct 27 16:31:40 CST 2018
     */
    public Byte getPaidMethod() {
        return paidMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_paid_fee_detail.paid_method
     *
     * @param paidMethod the value for z_paid_fee_detail.paid_method
     *
     * @mbg.generated Sat Oct 27 16:31:40 CST 2018
     */
    public void setPaidMethod(Byte paidMethod) {
        this.paidMethod = paidMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_paid_fee_detail.electric
     *
     * @return the value of z_paid_fee_detail.electric
     *
     * @mbg.generated Sat Oct 27 16:31:40 CST 2018
     */
    public Integer getElectric() {
        return electric;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_paid_fee_detail.electric
     *
     * @param electric the value for z_paid_fee_detail.electric
     *
     * @mbg.generated Sat Oct 27 16:31:40 CST 2018
     */
    public void setElectric(Integer electric) {
        this.electric = electric;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_paid_fee_detail.paid_man
     *
     * @return the value of z_paid_fee_detail.paid_man
     *
     * @mbg.generated Sat Oct 27 16:31:40 CST 2018
     */
    public String getPaidMan() {
        return paidMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_paid_fee_detail.paid_man
     *
     * @param paidMan the value for z_paid_fee_detail.paid_man
     *
     * @mbg.generated Sat Oct 27 16:31:40 CST 2018
     */
    public void setPaidMan(String paidMan) {
        this.paidMan = paidMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_paid_fee_detail.charge_man
     *
     * @return the value of z_paid_fee_detail.charge_man
     *
     * @mbg.generated Sat Oct 27 16:31:40 CST 2018
     */
    public String getChargeMan() {
        return chargeMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_paid_fee_detail.charge_man
     *
     * @param chargeMan the value for z_paid_fee_detail.charge_man
     *
     * @mbg.generated Sat Oct 27 16:31:40 CST 2018
     */
    public void setChargeMan(String chargeMan) {
        this.chargeMan = chargeMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_paid_fee_detail.remarks
     *
     * @return the value of z_paid_fee_detail.remarks
     *
     * @mbg.generated Sat Oct 27 16:31:40 CST 2018
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_paid_fee_detail.remarks
     *
     * @param remarks the value for z_paid_fee_detail.remarks
     *
     * @mbg.generated Sat Oct 27 16:31:40 CST 2018
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_paid_fee_detail.fee_type
     *
     * @return the value of z_paid_fee_detail.fee_type
     *
     * @mbg.generated Sat Oct 27 16:31:40 CST 2018
     */
    public Boolean getFeeType() {
        return feeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_paid_fee_detail.fee_type
     *
     * @param feeType the value for z_paid_fee_detail.fee_type
     *
     * @mbg.generated Sat Oct 27 16:31:40 CST 2018
     */
    public void setFeeType(Boolean feeType) {
        this.feeType = feeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_paid_fee_detail.status
     *
     * @return the value of z_paid_fee_detail.status
     *
     * @mbg.generated Sat Oct 27 16:31:40 CST 2018
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_paid_fee_detail.status
     *
     * @param status the value for z_paid_fee_detail.status
     *
     * @mbg.generated Sat Oct 27 16:31:40 CST 2018
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_paid_fee_detail.create_emp_id
     *
     * @return the value of z_paid_fee_detail.create_emp_id
     *
     * @mbg.generated Sat Oct 27 16:31:40 CST 2018
     */
    public Integer getCreateEmpId() {
        return createEmpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_paid_fee_detail.create_emp_id
     *
     * @param createEmpId the value for z_paid_fee_detail.create_emp_id
     *
     * @mbg.generated Sat Oct 27 16:31:40 CST 2018
     */
    public void setCreateEmpId(Integer createEmpId) {
        this.createEmpId = createEmpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_paid_fee_detail.create_emp
     *
     * @return the value of z_paid_fee_detail.create_emp
     *
     * @mbg.generated Sat Oct 27 16:31:40 CST 2018
     */
    public String getCreateEmp() {
        return createEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_paid_fee_detail.create_emp
     *
     * @param createEmp the value for z_paid_fee_detail.create_emp
     *
     * @mbg.generated Sat Oct 27 16:31:40 CST 2018
     */
    public void setCreateEmp(String createEmp) {
        this.createEmp = createEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_paid_fee_detail.create_time
     *
     * @return the value of z_paid_fee_detail.create_time
     *
     * @mbg.generated Sat Oct 27 16:31:40 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_paid_fee_detail.create_time
     *
     * @param createTime the value for z_paid_fee_detail.create_time
     *
     * @mbg.generated Sat Oct 27 16:31:40 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_paid_fee_detail.modify_emp_id
     *
     * @return the value of z_paid_fee_detail.modify_emp_id
     *
     * @mbg.generated Sat Oct 27 16:31:40 CST 2018
     */
    public Integer getModifyEmpId() {
        return modifyEmpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_paid_fee_detail.modify_emp_id
     *
     * @param modifyEmpId the value for z_paid_fee_detail.modify_emp_id
     *
     * @mbg.generated Sat Oct 27 16:31:40 CST 2018
     */
    public void setModifyEmpId(Integer modifyEmpId) {
        this.modifyEmpId = modifyEmpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_paid_fee_detail.modify_emp
     *
     * @return the value of z_paid_fee_detail.modify_emp
     *
     * @mbg.generated Sat Oct 27 16:31:40 CST 2018
     */
    public String getModifyEmp() {
        return modifyEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_paid_fee_detail.modify_emp
     *
     * @param modifyEmp the value for z_paid_fee_detail.modify_emp
     *
     * @mbg.generated Sat Oct 27 16:31:40 CST 2018
     */
    public void setModifyEmp(String modifyEmp) {
        this.modifyEmp = modifyEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_paid_fee_detail.modify_time
     *
     * @return the value of z_paid_fee_detail.modify_time
     *
     * @mbg.generated Sat Oct 27 16:31:40 CST 2018
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_paid_fee_detail.modify_time
     *
     * @param modifyTime the value for z_paid_fee_detail.modify_time
     *
     * @mbg.generated Sat Oct 27 16:31:40 CST 2018
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}