package cn.zxy.zmanager.dao.dataobject;

public class ZUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_user.id
     *
     * @mbg.generated Sat Sep 22 12:27:13 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_user.account
     *
     * @mbg.generated Sat Sep 22 12:27:13 CST 2018
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_user.password
     *
     * @mbg.generated Sat Sep 22 12:27:13 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_user.create_time
     *
     * @mbg.generated Sat Sep 22 12:27:13 CST 2018
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_user.name
     *
     * @mbg.generated Sat Sep 22 12:27:13 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_user.role_type
     *
     * @mbg.generated Sat Sep 22 12:27:13 CST 2018
     */
    private Byte roleType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_user.update_time
     *
     * @mbg.generated Sat Sep 22 12:27:13 CST 2018
     */
    private String updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_user.id
     *
     * @return the value of z_user.id
     *
     * @mbg.generated Sat Sep 22 12:27:13 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_user.id
     *
     * @param id the value for z_user.id
     *
     * @mbg.generated Sat Sep 22 12:27:13 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_user.account
     *
     * @return the value of z_user.account
     *
     * @mbg.generated Sat Sep 22 12:27:13 CST 2018
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_user.account
     *
     * @param account the value for z_user.account
     *
     * @mbg.generated Sat Sep 22 12:27:13 CST 2018
     */
    public void setAccount(String account) {
        this.account = account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_user.password
     *
     * @return the value of z_user.password
     *
     * @mbg.generated Sat Sep 22 12:27:13 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_user.password
     *
     * @param password the value for z_user.password
     *
     * @mbg.generated Sat Sep 22 12:27:13 CST 2018
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_user.create_time
     *
     * @return the value of z_user.create_time
     *
     * @mbg.generated Sat Sep 22 12:27:13 CST 2018
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_user.create_time
     *
     * @param createTime the value for z_user.create_time
     *
     * @mbg.generated Sat Sep 22 12:27:13 CST 2018
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_user.name
     *
     * @return the value of z_user.name
     *
     * @mbg.generated Sat Sep 22 12:27:13 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_user.name
     *
     * @param name the value for z_user.name
     *
     * @mbg.generated Sat Sep 22 12:27:13 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_user.role_type
     *
     * @return the value of z_user.role_type
     *
     * @mbg.generated Sat Sep 22 12:27:13 CST 2018
     */
    public Byte getRoleType() {
        return roleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_user.role_type
     *
     * @param roleType the value for z_user.role_type
     *
     * @mbg.generated Sat Sep 22 12:27:13 CST 2018
     */
    public void setRoleType(Byte roleType) {
        this.roleType = roleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_user.update_time
     *
     * @return the value of z_user.update_time
     *
     * @mbg.generated Sat Sep 22 12:27:13 CST 2018
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_user.update_time
     *
     * @param updateTime the value for z_user.update_time
     *
     * @mbg.generated Sat Sep 22 12:27:13 CST 2018
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }
}