package cn.zxy.zmanager.dao.dataobject;

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;

public class ZWaterMeter {
	
	/** 状态：停止使用 */
	public static final Integer STOP_STATUS = 0;
	
	/** 状态：使用中 */
    public static final Integer USING_STATUS = 1;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_water_meter.id
     *
     * @mbg.generated Sat Oct 27 15:59:09 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_water_meter.water_meter_code
     *
     * @mbg.generated Sat Oct 27 15:59:09 CST 2018
     */
    private String waterMeterCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_water_meter.contract_id
     *
     * @mbg.generated Sat Oct 27 15:59:09 CST 2018
     */
    private Integer contractId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_water_meter.contract_code
     *
     * @mbg.generated Sat Oct 27 15:59:09 CST 2018
     */
    private String contractCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_water_meter.init_mark
     *
     * @mbg.generated Sat Oct 27 15:59:09 CST 2018
     */
    private Integer initMark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_water_meter.total_water
     *
     * @mbg.generated Sat Oct 27 15:59:09 CST 2018
     */
    private Integer totalWater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_water_meter.water_fee
     *
     * @mbg.generated Sat Oct 27 15:59:09 CST 2018
     */
    private Integer waterFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_water_meter.total_water_fee
     *
     * @mbg.generated Sat Oct 27 15:59:09 CST 2018
     */
    private Integer totalWaterFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_water_meter.paid_water_fee
     *
     * @mbg.generated Sat Oct 27 15:59:09 CST 2018
     */
    private Integer paidWaterFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_water_meter.status
     *
     * @mbg.generated Sat Oct 27 15:59:09 CST 2018
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_water_meter.remarks
     *
     * @mbg.generated Sat Oct 27 15:59:09 CST 2018
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_water_meter.create_time
     *
     * @mbg.generated Sat Oct 27 15:59:09 CST 2018
     */
    @JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_water_meter.create_emp
     *
     * @mbg.generated Sat Oct 27 15:59:09 CST 2018
     */
    private String createEmp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_water_meter.create_emp_id
     *
     * @mbg.generated Sat Oct 27 15:59:09 CST 2018
     */
    private Integer createEmpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_water_meter.modify_time
     *
     * @mbg.generated Sat Oct 27 15:59:09 CST 2018
     */
    @JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_water_meter.modify_emp_id
     *
     * @mbg.generated Sat Oct 27 15:59:09 CST 2018
     */
    private Integer modifyEmpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column z_water_meter.modify_emp
     *
     * @mbg.generated Sat Oct 27 15:59:09 CST 2018
     */
    private String modifyEmp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_water_meter.id
     *
     * @return the value of z_water_meter.id
     *
     * @mbg.generated Sat Oct 27 15:59:09 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_water_meter.id
     *
     * @param id the value for z_water_meter.id
     *
     * @mbg.generated Sat Oct 27 15:59:09 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_water_meter.water_meter_code
     *
     * @return the value of z_water_meter.water_meter_code
     *
     * @mbg.generated Sat Oct 27 15:59:09 CST 2018
     */
    public String getWaterMeterCode() {
        return waterMeterCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_water_meter.water_meter_code
     *
     * @param waterMeterCode the value for z_water_meter.water_meter_code
     *
     * @mbg.generated Sat Oct 27 15:59:09 CST 2018
     */
    public void setWaterMeterCode(String waterMeterCode) {
        this.waterMeterCode = waterMeterCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_water_meter.contract_id
     *
     * @return the value of z_water_meter.contract_id
     *
     * @mbg.generated Sat Oct 27 15:59:09 CST 2018
     */
    public Integer getContractId() {
        return contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_water_meter.contract_id
     *
     * @param contractId the value for z_water_meter.contract_id
     *
     * @mbg.generated Sat Oct 27 15:59:09 CST 2018
     */
    public void setContractId(Integer contractId) {
        this.contractId = contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_water_meter.contract_code
     *
     * @return the value of z_water_meter.contract_code
     *
     * @mbg.generated Sat Oct 27 15:59:09 CST 2018
     */
    public String getContractCode() {
        return contractCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_water_meter.contract_code
     *
     * @param contractCode the value for z_water_meter.contract_code
     *
     * @mbg.generated Sat Oct 27 15:59:09 CST 2018
     */
    public void setContractCode(String contractCode) {
        this.contractCode = contractCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_water_meter.init_mark
     *
     * @return the value of z_water_meter.init_mark
     *
     * @mbg.generated Sat Oct 27 15:59:09 CST 2018
     */
    public Integer getInitMark() {
        return initMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_water_meter.init_mark
     *
     * @param initMark the value for z_water_meter.init_mark
     *
     * @mbg.generated Sat Oct 27 15:59:09 CST 2018
     */
    public void setInitMark(Integer initMark) {
        this.initMark = initMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_water_meter.total_water
     *
     * @return the value of z_water_meter.total_water
     *
     * @mbg.generated Sat Oct 27 15:59:09 CST 2018
     */
    public Integer getTotalWater() {
        return totalWater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_water_meter.total_water
     *
     * @param totalWater the value for z_water_meter.total_water
     *
     * @mbg.generated Sat Oct 27 15:59:09 CST 2018
     */
    public void setTotalWater(Integer totalWater) {
        this.totalWater = totalWater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_water_meter.water_fee
     *
     * @return the value of z_water_meter.water_fee
     *
     * @mbg.generated Sat Oct 27 15:59:09 CST 2018
     */
    public Integer getWaterFee() {
        return waterFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_water_meter.water_fee
     *
     * @param waterFee the value for z_water_meter.water_fee
     *
     * @mbg.generated Sat Oct 27 15:59:09 CST 2018
     */
    public void setWaterFee(Integer waterFee) {
        this.waterFee = waterFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_water_meter.total_water_fee
     *
     * @return the value of z_water_meter.total_water_fee
     *
     * @mbg.generated Sat Oct 27 15:59:09 CST 2018
     */
    public Integer getTotalWaterFee() {
        return totalWaterFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_water_meter.total_water_fee
     *
     * @param totalWaterFee the value for z_water_meter.total_water_fee
     *
     * @mbg.generated Sat Oct 27 15:59:09 CST 2018
     */
    public void setTotalWaterFee(Integer totalWaterFee) {
        this.totalWaterFee = totalWaterFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_water_meter.paid_water_fee
     *
     * @return the value of z_water_meter.paid_water_fee
     *
     * @mbg.generated Sat Oct 27 15:59:09 CST 2018
     */
    public Integer getPaidWaterFee() {
        return paidWaterFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_water_meter.paid_water_fee
     *
     * @param paidWaterFee the value for z_water_meter.paid_water_fee
     *
     * @mbg.generated Sat Oct 27 15:59:09 CST 2018
     */
    public void setPaidWaterFee(Integer paidWaterFee) {
        this.paidWaterFee = paidWaterFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_water_meter.status
     *
     * @return the value of z_water_meter.status
     *
     * @mbg.generated Sat Oct 27 15:59:09 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_water_meter.status
     *
     * @param status the value for z_water_meter.status
     *
     * @mbg.generated Sat Oct 27 15:59:09 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_water_meter.remarks
     *
     * @return the value of z_water_meter.remarks
     *
     * @mbg.generated Sat Oct 27 15:59:09 CST 2018
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_water_meter.remarks
     *
     * @param remarks the value for z_water_meter.remarks
     *
     * @mbg.generated Sat Oct 27 15:59:09 CST 2018
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_water_meter.create_time
     *
     * @return the value of z_water_meter.create_time
     *
     * @mbg.generated Sat Oct 27 15:59:09 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_water_meter.create_time
     *
     * @param createTime the value for z_water_meter.create_time
     *
     * @mbg.generated Sat Oct 27 15:59:09 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_water_meter.create_emp
     *
     * @return the value of z_water_meter.create_emp
     *
     * @mbg.generated Sat Oct 27 15:59:09 CST 2018
     */
    public String getCreateEmp() {
        return createEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_water_meter.create_emp
     *
     * @param createEmp the value for z_water_meter.create_emp
     *
     * @mbg.generated Sat Oct 27 15:59:09 CST 2018
     */
    public void setCreateEmp(String createEmp) {
        this.createEmp = createEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_water_meter.create_emp_id
     *
     * @return the value of z_water_meter.create_emp_id
     *
     * @mbg.generated Sat Oct 27 15:59:09 CST 2018
     */
    public Integer getCreateEmpId() {
        return createEmpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_water_meter.create_emp_id
     *
     * @param createEmpId the value for z_water_meter.create_emp_id
     *
     * @mbg.generated Sat Oct 27 15:59:09 CST 2018
     */
    public void setCreateEmpId(Integer createEmpId) {
        this.createEmpId = createEmpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_water_meter.modify_time
     *
     * @return the value of z_water_meter.modify_time
     *
     * @mbg.generated Sat Oct 27 15:59:09 CST 2018
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_water_meter.modify_time
     *
     * @param modifyTime the value for z_water_meter.modify_time
     *
     * @mbg.generated Sat Oct 27 15:59:09 CST 2018
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_water_meter.modify_emp_id
     *
     * @return the value of z_water_meter.modify_emp_id
     *
     * @mbg.generated Sat Oct 27 15:59:09 CST 2018
     */
    public Integer getModifyEmpId() {
        return modifyEmpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_water_meter.modify_emp_id
     *
     * @param modifyEmpId the value for z_water_meter.modify_emp_id
     *
     * @mbg.generated Sat Oct 27 15:59:09 CST 2018
     */
    public void setModifyEmpId(Integer modifyEmpId) {
        this.modifyEmpId = modifyEmpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column z_water_meter.modify_emp
     *
     * @return the value of z_water_meter.modify_emp
     *
     * @mbg.generated Sat Oct 27 15:59:09 CST 2018
     */
    public String getModifyEmp() {
        return modifyEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column z_water_meter.modify_emp
     *
     * @param modifyEmp the value for z_water_meter.modify_emp
     *
     * @mbg.generated Sat Oct 27 15:59:09 CST 2018
     */
    public void setModifyEmp(String modifyEmp) {
        this.modifyEmp = modifyEmp;
    }
    
    public static ZWaterRecord genWaterMeterRecord(ZWaterMeter meter) {
    	ZWaterRecord record = new ZWaterRecord();
    	record.setContractCode(meter.getContractCode());
    	record.setContractId(meter.getContractId());
    	record.setStartMark(meter.getInitMark() + meter.getTotalWater());
    	record.setWaterMeterCode(meter.getWaterMeterCode());
    	record.setWaterMeterId(meter.getId());
    	record.setWaterFee(meter.getWaterFee());
    	
    	return record;
    }
    
    public static ZContract genContract(ZWaterMeter meter) {
    	ZContract e = new ZContract();
    	e.setId(meter.getContractId());
    	e.setTotalUseWater(meter.getTotalWater());
    	
    	return e;
    }
}