package cn.zxy.zmanager.dao.mapper;

import cn.zxy.zmanager.dao.dataobject.ZContractHouse;
import cn.zxy.zmanager.dao.dataobject.ZContractHouseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ZContractHouseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_contract_house
     *
     * @mbg.generated Mon Oct 15 20:23:05 CST 2018
     */
    long countByExample(ZContractHouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_contract_house
     *
     * @mbg.generated Mon Oct 15 20:23:05 CST 2018
     */
    int deleteByExample(ZContractHouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_contract_house
     *
     * @mbg.generated Mon Oct 15 20:23:05 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_contract_house
     *
     * @mbg.generated Mon Oct 15 20:23:05 CST 2018
     */
    int insert(ZContractHouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_contract_house
     *
     * @mbg.generated Mon Oct 15 20:23:05 CST 2018
     */
    int insertSelective(ZContractHouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_contract_house
     *
     * @mbg.generated Mon Oct 15 20:23:05 CST 2018
     */
    List<ZContractHouse> selectByExample(ZContractHouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_contract_house
     *
     * @mbg.generated Mon Oct 15 20:23:05 CST 2018
     */
    ZContractHouse selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_contract_house
     *
     * @mbg.generated Mon Oct 15 20:23:05 CST 2018
     */
    int updateByExampleSelective(@Param("record") ZContractHouse record, @Param("example") ZContractHouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_contract_house
     *
     * @mbg.generated Mon Oct 15 20:23:05 CST 2018
     */
    int updateByExample(@Param("record") ZContractHouse record, @Param("example") ZContractHouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_contract_house
     *
     * @mbg.generated Mon Oct 15 20:23:05 CST 2018
     */
    int updateByPrimaryKeySelective(ZContractHouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_contract_house
     *
     * @mbg.generated Mon Oct 15 20:23:05 CST 2018
     */
    int updateByPrimaryKey(ZContractHouse record);

	void batchInsert(@Param("list") List<ZContractHouse> contractHouseList);
}