package cn.zxy.zmanager.dao.mapper;

import cn.zxy.zmanager.dao.dataobject.ZElectricMeter;
import cn.zxy.zmanager.dao.dataobject.ZElectricMeterExample;
import cn.zxy.zmanager.support.LoginUser;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ZElectricMeterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_electric_meter
     *
     * @mbg.generated Sat Oct 27 15:56:51 CST 2018
     */
    long countByExample(ZElectricMeterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_electric_meter
     *
     * @mbg.generated Sat Oct 27 15:56:51 CST 2018
     */
    int deleteByExample(ZElectricMeterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_electric_meter
     *
     * @mbg.generated Sat Oct 27 15:56:51 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_electric_meter
     *
     * @mbg.generated Sat Oct 27 15:56:51 CST 2018
     */
    int insert(ZElectricMeter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_electric_meter
     *
     * @mbg.generated Sat Oct 27 15:56:51 CST 2018
     */
    int insertSelective(ZElectricMeter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_electric_meter
     *
     * @mbg.generated Sat Oct 27 15:56:51 CST 2018
     */
    List<ZElectricMeter> selectByExample(ZElectricMeterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_electric_meter
     *
     * @mbg.generated Sat Oct 27 15:56:51 CST 2018
     */
    ZElectricMeter selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_electric_meter
     *
     * @mbg.generated Sat Oct 27 15:56:51 CST 2018
     */
    int updateByExampleSelective(@Param("record") ZElectricMeter record, @Param("example") ZElectricMeterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_electric_meter
     *
     * @mbg.generated Sat Oct 27 15:56:51 CST 2018
     */
    int updateByExample(@Param("record") ZElectricMeter record, @Param("example") ZElectricMeterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_electric_meter
     *
     * @mbg.generated Sat Oct 27 15:56:51 CST 2018
     */
    int updateByPrimaryKeySelective(ZElectricMeter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_electric_meter
     *
     * @mbg.generated Sat Oct 27 15:56:51 CST 2018
     */
    int updateByPrimaryKey(ZElectricMeter record);

	List<ZElectricMeter> selectByContractIdList(@Param("list") List<Integer> contractIdList);

	List<ZElectricMeter> selectByCodeList(@Param("list") List<String> excelMeterCodeList);

	int updateBatchSelective(@Param("list") List<ZElectricMeter> newElectricMeterList, @Param("user") LoginUser loginUser);
}