package cn.zxy.zmanager.dao.mapper;

import cn.zxy.zmanager.dao.dataobject.ZUser;
import cn.zxy.zmanager.dao.dataobject.ZUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ZUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_user
     *
     * @mbg.generated Sat Sep 22 12:27:13 CST 2018
     */
    long countByExample(ZUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_user
     *
     * @mbg.generated Sat Sep 22 12:27:13 CST 2018
     */
    int deleteByExample(ZUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_user
     *
     * @mbg.generated Sat Sep 22 12:27:13 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_user
     *
     * @mbg.generated Sat Sep 22 12:27:13 CST 2018
     */
    int insert(ZUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_user
     *
     * @mbg.generated Sat Sep 22 12:27:13 CST 2018
     */
    int insertSelective(ZUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_user
     *
     * @mbg.generated Sat Sep 22 12:27:13 CST 2018
     */
    List<ZUser> selectByExample(ZUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_user
     *
     * @mbg.generated Sat Sep 22 12:27:13 CST 2018
     */
    ZUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_user
     *
     * @mbg.generated Sat Sep 22 12:27:13 CST 2018
     */
    int updateByExampleSelective(@Param("record") ZUser record, @Param("example") ZUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_user
     *
     * @mbg.generated Sat Sep 22 12:27:13 CST 2018
     */
    int updateByExample(@Param("record") ZUser record, @Param("example") ZUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_user
     *
     * @mbg.generated Sat Sep 22 12:27:13 CST 2018
     */
    int updateByPrimaryKeySelective(ZUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_user
     *
     * @mbg.generated Sat Sep 22 12:27:13 CST 2018
     */
    int updateByPrimaryKey(ZUser record);
}