package cn.zxy.zmanager.dao.mapper;

import cn.zxy.zmanager.dao.dataobject.ZWaterRecord;
import cn.zxy.zmanager.dao.dataobject.ZWaterRecordExample;
import cn.zxy.zmanager.support.LoginUser;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ZWaterRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_water_record
     *
     * @mbg.generated Sat Oct 27 16:32:51 CST 2018
     */
    long countByExample(ZWaterRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_water_record
     *
     * @mbg.generated Sat Oct 27 16:32:51 CST 2018
     */
    int deleteByExample(ZWaterRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_water_record
     *
     * @mbg.generated Sat Oct 27 16:32:51 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_water_record
     *
     * @mbg.generated Sat Oct 27 16:32:51 CST 2018
     */
    int insert(ZWaterRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_water_record
     *
     * @mbg.generated Sat Oct 27 16:32:51 CST 2018
     */
    int insertSelective(ZWaterRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_water_record
     *
     * @mbg.generated Sat Oct 27 16:32:51 CST 2018
     */
    List<ZWaterRecord> selectByExample(ZWaterRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_water_record
     *
     * @mbg.generated Sat Oct 27 16:32:51 CST 2018
     */
    ZWaterRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_water_record
     *
     * @mbg.generated Sat Oct 27 16:32:51 CST 2018
     */
    int updateByExampleSelective(@Param("record") ZWaterRecord record, @Param("example") ZWaterRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_water_record
     *
     * @mbg.generated Sat Oct 27 16:32:51 CST 2018
     */
    int updateByExample(@Param("record") ZWaterRecord record, @Param("example") ZWaterRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_water_record
     *
     * @mbg.generated Sat Oct 27 16:32:51 CST 2018
     */
    int updateByPrimaryKeySelective(ZWaterRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_water_record
     *
     * @mbg.generated Sat Oct 27 16:32:51 CST 2018
     */
    int updateByPrimaryKey(ZWaterRecord record);

	int insertBatch(@Param("list") List<ZWaterRecord> recordList, @Param("user") LoginUser loginUser);
}